/*
 Apache-2.0
*/
(function(v,b){"function"===typeof define&&define.amd?define(["backbone","exports"],function(x,M){v.Augmented=b(v,M,x)}):"undefined"!==typeof exports?(require("backbone"),b(v,exports,Backbone)):v.Augmented=b(v,{},v.Backbone)})(this,function(v,b,x){var M=v.Augmented;b.VERSION="0.1.0";b.codename="Adam Jensen";b.releasename="Tai Yong";b.noConflict=function(){v.Augmented=M;x.noConflict();return this};b._=x._;b.$=x.$;b.Configuration={LoggerLevel:"debug",MessageBundle:"Messages",AsynchronousQueueTimeout:2E3,
ApplicationInitProcessTimeout:1E3};b.extend=x.Model.extend;b.sync=x.sync;b.isFunction=function(a){return"[object Function]"==Object.prototype.toString.call(a)};b.result=function(a,d){if(null!==a){var e=a[d];return b.isFunction(e)?e.call(a):e}};Array.prototype.includes||(Array.prototype.includes=function(a,d){var e=Object(this),b=parseInt(e.length)||0;if(0===b)return!1;var m=parseInt(d)||0;0<=m||(m=b+m,0>m&&(m=0));for(var n;m<b;){n=e[m];if(a===n||a!==a&&n!==n)return!0;m++}return!1});Array.prototype.has=
function(a){return-1!==this.indexOf(a)};b.Utility={};var q=b.Utility.TransformerType={string:0,integer:1,number:2,"boolean":3,array:4,object:5,"null":6};b.Utility.Transformer={type:q,transform:function(a,d){var e=null;switch(d){case q.string:e="object"===typeof a?JSON.stringify(a):String(a);break;case q.integer:e=parseInt(a);break;case q.number:e=Number(a);break;case q["boolean"]:e=Boolean(a);break;case q.array:Array.isArray(a)?e=a:(e=[],e[0]=a);break;case q.object:"object"!==typeof a?(e={},e[a]=
a):e=a}return e},isType:function(a){if(null===a)return q["null"];if("string"===typeof a)return q.string;if("number"===typeof a)return q.number;if("boolean"===typeof a)return q["boolean"];if(Array.isArray(a))return q.array;if("object"===typeof a)return q.object}};b.Utility.isString=function(a){return"string"===typeof a||!!a&&"object"===typeof a&&"[object String]"===Object.prototype.toString.call(a)};b.Utility.extend=function(){for(var a=1;a<arguments.length;a++)for(var d in arguments[a])arguments[a].hasOwnProperty(d)&&
(arguments[0][d]=arguments[a][d]);return arguments[0]};var Q=XMLHttpRequest;b.Utility.extend(Q,{done:function(){},fail:function(){},always:function(){},then:function(){}});var S=function(){this.responseType="text";this.responseText="";this.async=!0;this.status=200;this.header={};this.timeout=70;this.open=function(a,d,e,b,m){this.url=d;this.async=e;this.user=b;this.method=a};this.send=function(){this.onload()};this.setRequestHeader=function(a,d){this.header.header=d};this.done=function(){};this.fail=
function(){};this.always=function(){};this.then=function(){};this.options={}};b.Ajax={};b.Ajax.Configuration={url:"localhost",contentType:"text/plain",dataType:"text",async:!0};var I=b.ajax=b.Ajax.ajax=function(a){C.debug("Ajax object: "+JSON.stringify(a));var d=null;if(a&&a.url){var e=a.method?a.method:"GET",b=a.cache?a.cache:!0,d=a.mock?new S:new Q;a.timeout&&(d.timeout=a.timeout);var m=void 0!==a.async?a.async:!0;a.withCredentials&&(d.withCredentials=a.withCredentials,C.warn("Augmented.ajax: Sync Not supported for all browsers in CORS mode!"),
m=!0);m&&a.dataType&&(d.responseType=a.dataType?a.dataType:"text");d.open(e,encodeURI(a.url),m,void 0!==a.user?a.user:"",void 0!==a.password?a.password:"");d.setRequestHeader("Content-Type",a.contentType?a.contentType:"text/plain");b||d.setRequestHeader("Cache-Control","no-cache");d.onload=function(){199<d.status&&300>d.status?a.success&&a.success(d.responseText,d.status):399<d.status&&600>d.status&&a.failure&&a.failure(d.responseText,d.status);a.complete&&a.complete(d.responseText,d.status);return d};
a.beforeSend&&a.beforeSend(d);d.send()}this.done=function(){};this.fail=function(){};this.always=function(){};this.then=function(){};return this};x.ajax=I;b.Logger={};var N=b.Logger.Type={console:"console",rest:"rest"},p=b.Logger.Level={info:"info",debug:"debug",error:"error",warn:"warn"},J=function(a){this.TIME_SEPERATOR=":";this.DATE_SEPERATOR="-";this.OPEN_GROUP=" [ ";this.CLOSE_GROUP=" ] ";this.label=p;this.loggerLevel=a?a:p.info;this.getLogTime=function(){var a=new Date;return a.getFullYear()+
this.DATE_SEPERATOR+(a.getMonth()+1)+this.DATE_SEPERATOR+a.getDate()+" "+a.getHours()+this.TIME_SEPERATOR+a.getMinutes()+this.TIME_SEPERATOR+a.getSeconds()+this.TIME_SEPERATOR+a.getMilliseconds()};this.log=function(a,e){a&&(e||(e=p.info),this.loggerLevel===p.debug&&e===p.debug?this.logMe(this.getLogTime()+this.OPEN_GROUP+p.debug+this.CLOSE_GROUP+a,e):e===p.error?this.logMe(this.getLogTime()+this.OPEN_GROUP+p.error+this.CLOSE_GROUP+a,e):e===p.warn?this.logMe(this.getLogTime()+this.OPEN_GROUP+p.warn+
this.CLOSE_GROUP+a,e):this.loggerLevel!==p.debug&&this.loggerLevel!==p.info||this.logMe(this.getLogTime()+this.OPEN_GROUP+p.info+this.CLOSE_GROUP+a,e))};this.info=function(a){this.log(a,p.info)};this.error=function(a){this.log(a,p.error)};this.debug=function(a){this.log(a,p.debug)};this.warn=function(a){this.log(a,p.warn)}},G=function(){J.apply(this,arguments)};G.prototype=Object.create(J.prototype);G.prototype.constructor=G;G.prototype.logMe=function(a,d){d===p.info?console.info(a):d===p.error?console.error(a):
d===p.debug?console.log(a):d===p.warn?console.warn(a):console.log(a)};var F=function(){J.apply(this,arguments)};F.prototype=Object.create(J.prototype);F.prototype.constructor=F;F.prototype.setURI=function(a){this.uri=a};F.prototype.logMe=function(a){I({url:this.uri,method:"POST",contentType:"text/plain",dataType:"text",async:!0,data:a,success:function(a,e){this.success()},failure:function(a,e){this.failure()}})};b.Logger.LoggerFactory={getLogger:function(a,d){if(a===N.console)return new G(d);if(a===
N.rest)return new F(d)}};var C=b.Logger.LoggerFactory.getLogger(N.console,b.Configuration.LoggerLevel);b.Utility.wrap=function(a,d){return function(){return d.apply(this,[a].concat(Array.prototype.slice.call(arguments)))}};b.Utility.Array=function(a){this.has=function(d){return a.has(d)}};b.Utility.AugmentedMap=function(a){this.keys=[];this.data={};this.set=function(a,e){null!==a&&null!==e&&(this.data[a]||this.keys.push(a),this.data[a]=e)};this.get=function(a){return this.data[a]};this.indexOf=function(a){return this.keys.indexOf(a)};
this.remove=function(a){var e=this.indexOf(a);this.keys.splice(e,1);delete this.data[a]};this.has=function(a){return-1!==this.indexOf(a)};this.forEach=function(a){if("function"===typeof a)for(var e=this.keys.length,b=0,m,b=0;b<e;b++)m=this.keys[b],a(m,this.data[m],b)};this.key=function(a){return this.keys[a]};this.entries=function(){for(var a=this.keys.length,e=Array(a),b=0;b<a;b++)e[b]={key:this.keys[b],value:this.data[b]};return e};this.values=function(){for(var a=this.keys.length,e=Array(a),b=
0;b<a;b++)e[b]=this.data[b];return e};this.clear=function(){this.keys=[];this.data={}};this.size=function(){return this.keys.length};this.toJSON=function(){return this.data};this.toString=function(){return JSON.stringify(this.data)};this.isEmpty=function(){return 0===this.keys.length};this.marshall=function(a){if(a&&a instanceof b.Utility.AugmentedMap)a=a.toJSON();else if(!(a&&a instanceof Object&&0<Object.keys(a).length))return C.warn("Could not marshall data: "+JSON.stringify(a)),!1;for(var e=Object.keys(a),
r=0;r<e.length;r++){var m=e[r],n=a[m];C.debug("setting "+m+", "+n);this.set(m,n)}return!0};if(a)return this.marshall(a)};b.Object=function(a){this.options=b.Utility.extend({},b.result(this,"options"),a);this.initialize.apply(this,arguments)};b.Object.extend=b.extend;b.Utility.extend(b.Object.prototype,x.Events,{initialize:function(){}});b.Security={};b.Security.Client={};var T=b.Security.Principal={fullName:"",id:0,login:"",email:""},U=b.Security.Context=function(a,d){this.principal=a?a:(new a).login=
"guest";this.permissions=d?d:[];this.getPrincipal=function(){return this.principal};this.getPermissions=function(){return this.permissions};this.setPermissions=function(a){this.permissions=a};this.addPermission=function(a){this.permissions.push(a)};this.removePermission=function(a){a=this.permissions.indexOf(a);this.permissions.splice(a,1)};this.hasPermission=function(a){return-1!=this.permissions.indexOf(a)}};b.Security.ClientType={OAUTH2:0,ACL:1};var D=b.Object.extend({type:null,uri:""});b.Security.Client.OAUTH2Client=
D.extend({type:b.Security.ClientType.OAUTH2,accessToken:"",authorizationToken:"",authorize:function(a){this.authorizationToken=""},access:function(a){this.accessToken=""}});b.Security.Client.ACLClient=D.extend({type:b.Security.ClientType.ACL,authenticate:function(a,d){var b=null;I({url:this.uri,method:"GET",user:a,password:d,success:function(a,d){var n=new T({fullName:a.fullName,id:a.id,login:a.login,email:a.email});b=new U(n,a.permissions)},failure:function(a,d){throw Error("Failed to authenticate with response of - "+
d);}});return b}});b.Security.AuthenticationFactory={getSecurityClient:function(a){return a===b.Security.ClientType.OAUTH2?new b.Security.Client.OAUTH2Client:a===b.Security.ClientType.ACL?new b.Security.Client.ACLClient:null}};b.Security.Entry=function(a,d){this.permissions=a?a:[];this.isNegative=d?d:!1;this.getPermissions=function(){return this.permissions};this.setPermissions=function(a){this.permissions=a};this.addPermission=function(a){this.permissions.push(a)};this.removePermission=function(a){a=
this.permissions.indexOf(a);this.permissions.splice(a,1)};this.hasPermission=function(a){return-1!=this.permissions.indexOf(a)};this.setNegative=function(a){this.isNegative=a}};var V=function(){function a(f){return encodeURI(f).replace(/%25[0-9][0-9]/g,function(f){return"%"+f.substring(3)})}function d(f){var c="";K[f.charAt(0)]&&(c=f.charAt(0),f=f.substring(1));var t="",z="",B=!0,b=!1,d=!1;"+"===c?B=!1:"."===c?t=z=".":"/"===c?t=z="/":"#"===c?(z="#",B=!1):";"===c?(t=z=";",d=b=!0):"?"===c?(z="?",t=
"&",b=!0):"&"===c&&(t=z="&",b=!0);c=[];f=f.split(",");for(var e=[],h=0;h<f.length;h++){var k=f[h],n=null;-1!==k.indexOf(":")&&(n=k.split(":"),k=n[0],n=parseInt(n[1],10));for(var g={};x[k.charAt(k.length-1)];)g[k.charAt(k.length-1)]=!0,k=k.substring(0,k.length-1);e.push({truncate:n,name:k,suffices:g});c.push(k)}f=function(f){for(var c="",h=0,k=0;k<e.length;k++){var n=e[k],g=f(n.name);if(null===g||void 0===g||Array.isArray(g)&&0===g.length||"object"===typeof g&&0===Object.keys(g).length)h++;else if(c=
k===h?c+z:c+(t||","),Array.isArray(g)){b&&(c+=n.name+"=");for(var l=0;l<g.length;l++)0<l&&(c+=n.suffices["*"]?t||",":",",n.suffices["*"]&&b&&(c+=n.name+"=")),c+=B?encodeURIComponent(g[l]).replace(/!/g,"%21"):a(g[l])}else if("object"===typeof g){b&&!n.suffices["*"]&&(c+=n.name+"=");var l=!0,w;for(w in g)l||(c+=n.suffices["*"]?t||",":","),l=!1,c+=B?encodeURIComponent(w).replace(/!/g,"%21"):a(w),c+=n.suffices["*"]?"=":",",c+=B?encodeURIComponent(g[w]).replace(/!/g,"%21"):a(g[w])}else b&&(c+=n.name,d&&
""===g||(c+="=")),null!==n.truncate&&(g=g.substring(0,n.truncate)),c+=B?encodeURIComponent(g).replace(/!/g,"%21"):a(g)}return c};f.varNames=c;return{prefix:z,substitution:f}}function b(f){if(!(this instanceof b))return new b(f);for(var c=f.split("{"),a=[c.shift()],z=[],B=[],h=[];0<c.length;){var g=c.shift(),k=g.split("}")[0],g=g.substring(k.length+1),k=d(k);B.push(k.substitution);z.push(k.prefix);a.push(g);h=h.concat(k.substitution.varNames)}this.fill=function(f){for(var c=a[0],z=0;z<B.length;z++)c+=
(0,B[z])(f),c+=a[z+1];return c};this.varNames=h;this.template=f}function r(f,c){if(f===c)return!0;if("object"===typeof f&&"object"===typeof c){if(Array.isArray(f)!==Array.isArray(c))return!1;if(Array.isArray(f)){if(f.length!==c.length)return!1;for(var a=0;a<f.length;a++)if(!r(f[a],c[a]))return!1}else{for(a in f)if(void 0===c[a]&&void 0!==f[a])return!1;for(a in c)if(void 0===f[a]&&void 0!==c[a])return!1;for(a in f)if(!r(f[a],c[a]))return!1}return!0}return!1}function m(f){return(f=String(f).replace(/^\s+|\s+$/g,
"").match(/^([^:\/?#]+:)?(\/\/(?:[^:@]*(?::[^:@]*)?@)?(([^:\/?#]*)(?::(\d*))?))?([^?#]*)(\?[^#]*)?(#[\s\S]*)?/))?{href:f[0]||"",protocol:f[1]||"",authority:f[2]||"",host:f[3]||"",hostname:f[4]||"",port:f[5]||"",pathname:f[6]||"",search:f[7]||"",hash:f[8]||""}:null}function n(f,c){function a(f){var c=[];f.replace(/^(\.\.?(\/|$))+/,"").replace(/\/(\.(\/|$))+/g,"/").replace(/\/\.\.$/,"/../").replace(/\/?[^\/]*/g,function(f){"/.."===f?c.pop():c.push(f)});return c.join("").replace(/^\//,"/"===f.charAt(0)?
"/":"")}c=m(c||"");f=m(f||"");return c&&f?(c.protocol||f.protocol)+(c.protocol||c.authority?c.authority:f.authority)+a(c.protocol||c.authority||"/"===c.pathname.charAt(0)?c.pathname:c.pathname?(f.authority&&!f.pathname?"/":"")+f.pathname.slice(0,f.pathname.lastIndexOf("/")+1)+c.pathname:f.pathname)+(c.protocol||c.authority||c.pathname?c.search:c.search||f.search)+c.hash:null}function h(f){return f.split("#")[0]}function w(f,c){if(f&&"object"===typeof f)if(void 0===c?c=f.id:"string"===typeof f.id&&
(c=n(c,f.id),f.id=c),Array.isArray(f))for(var a=0;a<f.length;a++)w(f[a],c);else for(a in"string"===typeof f.$ref&&(f.$ref=n(c,f.$ref)),f)"enum"!==a&&w(f[a],c)}function k(f,a,t,z,B,b){Error.call(this);if(void 0===f)throw Error("No code supplied for error: "+a);this.message=a;this.params=t;this.code=f;this.dataPath=z||"";this.schemaPath=B||"";this.subErrors=b||null;f=Error(this.message);this.stack=f.stack||f.stacktrace;if(!this.stack)try{throw f;}catch(d){this.stack=d.stack||d.stacktrace}}function p(f){var a=
new g,t=f||"en";return{addFormat:function(){a.addFormat.apply(a,arguments)},language:function(a){if(!a)return t;u[a]||(a=a.split("-")[0]);return u[a]?t=a:!1},addLanguage:function(a,f){for(var c in l)f[c]&&!f[l[c]]&&(f[l[c]]=f[c]);var t=a.split("-")[0];if(u[t])for(c in u[a]=Object.create(u[t]),f)"undefined"===typeof u[t][c]&&(u[t][c]=f[c]),u[a][c]=f[c];else u[a]=f,u[t]=f;return this},freshApi:function(a){var f=p();a&&f.language(a);return f},validate:function(f,b,d,e){d=new g(a,!1,u[t],d,e);"string"===
typeof b&&(b={$ref:b});d.addSchema("",b);f=d.validateAll(f,b,null,null,"");!f&&e&&(f=d.banUnknownProperties());this.error=f;this.missing=d.missing;return this.valid=null===f},validateResult:function(){var a={};this.validate.apply(a,arguments);return a},validateMultiple:function(f,b,d,e){d=new g(a,!0,u[t],d,e);"string"===typeof b&&(b={$ref:b});d.addSchema("",b);d.validateAll(f,b,null,null,"");e&&d.banUnknownProperties();f={};f.errors=d.errors;f.missing=d.missing;f.valid=0===f.errors.length;return f},
addSchema:function(){return a.addSchema.apply(a,arguments)},getSchema:function(){return a.getSchema.apply(a,arguments)},getSchemaMap:function(){return a.getSchemaMap.apply(a,arguments)},getSchemaUris:function(){return a.getSchemaUris.apply(a,arguments)},getMissingUris:function(){return a.getMissingUris.apply(a,arguments)},dropSchemas:function(){a.dropSchemas.apply(a,arguments)},defineKeyword:function(){a.defineKeyword.apply(a,arguments)},defineError:function(a,f,c){if("string"!==typeof a||!/^[A-Z]+(_[A-Z]+)*$/.test(a))throw Error("Code name must be a string in UPPER_CASE_WITH_UNDERSCORES");
if("number"!==typeof f||0!==f%1||1E4>f)throw Error("Code number must be an integer > 10000");if("undefined"!==typeof l[a])throw Error("Error already defined: "+a+" as "+l[a]);if("undefined"!==typeof A[f])throw Error("Error code already used: "+A[f]+" as "+f);l[a]=f;A[f]=a;v[a]=v[f]=c;for(var b in u)c=u[b],c[a]&&(c[f]=c[f]||c[a])},reset:function(){a.reset();this.error=null;this.missing=[];this.valid=!0},missing:[],error:null,valid:!0,normSchema:w,resolveUrl:n,getDocumentUri:h,errorCodes:l}}var K={"+":!0,
"#":!0,".":!0,"/":!0,";":!0,"?":!0,"&":!0},x={"*":!0};b.prototype={toString:function(){return this.template},fillFromObject:function(a){return this.fill(function(c){return a[c]})}};var g=function(a,c,b,d,e){this.missing=[];this.missingMap={};this.formatValidators=a?Object.create(a.formatValidators):{};this.schemas=a?Object.create(a.schemas):{};this.collectMultiple=c;this.errors=[];this.handleError=c?this.collectError:this.returnError;d&&(this.checkRecursive=!0,this.scanned=[],this.scannedFrozen=[],
this.scannedFrozenSchemas=[],this.scannedFrozenValidationErrors=[],this.validatedSchemasKey="tv4_validation_id",this.validationErrorsKey="tv4_validation_errors_id");e&&(this.trackUnknownProperties=!0,this.knownPropertyPaths={},this.unknownPropertyPaths={});this.errorMessages=b;this.definedKeywords={};if(a)for(var h in a.definedKeywords)this.definedKeywords[h]=a.definedKeywords[h].slice(0)};g.prototype.defineKeyword=function(a,c){this.definedKeywords[a]=this.definedKeywords[a]||[];this.definedKeywords[a].push(c)};
g.prototype.createError=function(a,c,b,d,e){var h=this.errorMessages[a]||v[a];if("string"!==typeof h)return new k(a,"Unknown error code "+a+": "+JSON.stringify(c),c,b,d,e);h=h.replace(/\{([^{}]*)\}/g,function(a,f){var b=c[f];return"string"===typeof b||"number"===typeof b?b:a});return new k(a,h,c,b,d,e)};g.prototype.returnError=function(a){return a};g.prototype.collectError=function(a){a&&this.errors.push(a);return null};g.prototype.prefixErrors=function(a,c,b){for(;a<this.errors.length;a++)this.errors[a]=
this.errors[a].prefixWith(c,b);return this};g.prototype.banUnknownProperties=function(){for(var a in this.unknownPropertyPaths){var c=this.createError(l.UNKNOWN_PROPERTY,{path:a},a,"");if(c=this.handleError(c))return c}return null};g.prototype.addFormat=function(a,c){if("object"===typeof a){for(var b in a)this.addFormat(b,a[b]);return this}this.formatValidators[a]=c};g.prototype.resolveRefs=function(a,c){if(void 0!==a.$ref){c=c||{};if(c[a.$ref])return this.createError(l.CIRCULAR_REFERENCE,{urls:Object.keys(c).join(", ")},
"","");c[a.$ref]=!0;a=this.getSchema(a.$ref,c)}return a};g.prototype.getSchema=function(a,c){var b;if(void 0!==this.schemas[a])return b=this.schemas[a],this.resolveRefs(b,c);var d=a,e="";-1!==a.indexOf("#")&&(e=a.substring(a.indexOf("#")+1),d=a.substring(0,a.indexOf("#")));if("object"===typeof this.schemas[d]){b=this.schemas[d];e=decodeURIComponent(e);if(""===e)return this.resolveRefs(b,c);if("/"!==e.charAt(0))return;for(var e=e.split("/").slice(1),h=0;h<e.length;h++){var k=e[h].replace(/~1/g,"/").replace(/~0/g,
"~");if(void 0===b[k]){b=void 0;break}b=b[k]}if(void 0!==b)return this.resolveRefs(b,c)}void 0===this.missing[d]&&(this.missing.push(d),this.missing[d]=d,this.missingMap[d]=d)};g.prototype.searchSchemas=function(a,c){if(Array.isArray(a))for(var b=0;b<a.length;b++)this.searchSchemas(a[b],c);else if(a&&"object"===typeof a){if("string"===typeof a.id){var d;a:{d=a.id;if(d.substring(0,c.length)===c){var e=d.substring(c.length);if(0<d.length&&"/"===d.charAt(c.length-1)||"#"===e.charAt(0)||"?"===e.charAt(0)){d=
!0;break a}}d=!1}d&&void 0===this.schemas[a.id]&&(this.schemas[a.id]=a)}for(b in a)"enum"!==b&&("object"===typeof a[b]?this.searchSchemas(a[b],c):"$ref"===b&&(d=h(a[b]))&&void 0===this.schemas[d]&&void 0===this.missingMap[d]&&(this.missingMap[d]=d))}};g.prototype.addSchema=function(a,c){if("string"!==typeof a||"undefined"===typeof c)if("object"===typeof a&&"string"===typeof a.id)c=a,a=c.id;else return;a===h(a)+"#"&&(a=h(a));this.schemas[a]=c;delete this.missingMap[a];w(c,a);this.searchSchemas(c,a)};
g.prototype.getSchemaMap=function(){var a={},c;for(c in this.schemas)a[c]=this.schemas[c];return a};g.prototype.getSchemaUris=function(a){var c=[],b;for(b in this.schemas)a&&!a.test(b)||c.push(b);return c};g.prototype.getMissingUris=function(a){var c=[],b;for(b in this.missingMap)a&&!a.test(b)||c.push(b);return c};g.prototype.dropSchemas=function(){this.schemas={};this.reset()};g.prototype.reset=function(){this.missing=[];this.missingMap={};this.errors=[]};g.prototype.validateAll=function(a,c,b,d,
e){var h;c=this.resolveRefs(c);if(!c)return null;if(c instanceof k)return this.errors.push(c),c;var g=this.errors.length,n,l=null,w=null;if(this.checkRecursive&&a&&"object"===typeof a){h=!this.scanned.length;if(a[this.validatedSchemasKey]){var m=a[this.validatedSchemasKey].indexOf(c);if(-1!==m)return this.errors=this.errors.concat(a[this.validationErrorsKey][m]),null}if(Object.isFrozen(a)&&(n=this.scannedFrozen.indexOf(a),-1!==n&&(m=this.scannedFrozenSchemas[n].indexOf(c),-1!==m)))return this.errors=
this.errors.concat(this.scannedFrozenValidationErrors[n][m]),null;this.scanned.push(a);if(Object.isFrozen(a))-1===n&&(n=this.scannedFrozen.length,this.scannedFrozen.push(a),this.scannedFrozenSchemas.push([])),l=this.scannedFrozenSchemas[n].length,this.scannedFrozenSchemas[n][l]=c,this.scannedFrozenValidationErrors[n][l]=[];else{if(!a[this.validatedSchemasKey])try{Object.defineProperty(a,this.validatedSchemasKey,{value:[],configurable:!0}),Object.defineProperty(a,this.validationErrorsKey,{value:[],
configurable:!0})}catch(r){a[this.validatedSchemasKey]=[],a[this.validationErrorsKey]=[]}w=a[this.validatedSchemasKey].length;a[this.validatedSchemasKey][w]=c;a[this.validationErrorsKey][w]=[]}}m=this.errors.length;c=this.validateBasic(a,c,e)||this.validateNumeric(a,c,e)||this.validateString(a,c,e)||this.validateArray(a,c,e)||this.validateObject(a,c,e)||this.validateCombinations(a,c,e)||this.validateHypermedia(a,c,e)||this.validateFormat(a,c,e)||this.validateDefinedKeywords(a,c,e)||null;if(h){for(;this.scanned.length;)delete this.scanned.pop()[this.validatedSchemasKey];
this.scannedFrozen=[];this.scannedFrozenSchemas=[]}if(c||m!==this.errors.length)for(;b&&b.length||d&&d.length;)h=b&&b.length?""+b.pop():null,e=d&&d.length?""+d.pop():null,c&&(c=c.prefixWith(h,e)),this.prefixErrors(m,h,e);null!==l?this.scannedFrozenValidationErrors[n][l]=this.errors.slice(g):null!==w&&(a[this.validationErrorsKey][w]=this.errors.slice(g));return this.handleError(c)};g.prototype.validateFormat=function(a,c){if("string"!==typeof c.format||!this.formatValidators[c.format])return null;
var b=this.formatValidators[c.format].call(null,a,c);return"string"===typeof b||"number"===typeof b?this.createError(l.FORMAT_CUSTOM,{message:b}).prefixWith(null,"format"):b&&"object"===typeof b?this.createError(l.FORMAT_CUSTOM,{message:b.message||"?"},b.dataPath||null,b.schemaPath||"/format"):null};g.prototype.validateDefinedKeywords=function(a,c,b){for(var d in this.definedKeywords)if("undefined"!==typeof c[d])for(var e=this.definedKeywords[d],h=0;h<e.length;h++){var k=(0,e[h])(a,c[d],c,b);if("string"===
typeof k||"number"===typeof k)return this.createError(l.KEYWORD_CUSTOM,{key:d,message:k}).prefixWith(null,"format");if(k&&"object"===typeof k){a=k.code;if("string"===typeof a){if(!l[a])throw Error("Undefined error code (use defineError): "+a);a=l[a]}else"number"!==typeof a&&(a=l.KEYWORD_CUSTOM);c="object"===typeof k.message?k.message:{key:d,message:k.message||"?"};d=k.schemaPath||"/"+d.replace(/~/g,"~0").replace(/\//g,"~1");return this.createError(a,c,k.dataPath||null,d)}}return null};g.prototype.validateBasic=
function(a,c,b){var d;return(d=this.validateType(a,c,b))||(d=this.validateEnum(a,c,b))?d.prefixWith(null,"type"):null};g.prototype.validateType=function(a,c){if(void 0===c.type)return null;var b=typeof a;null===a?b="null":Array.isArray(a)&&(b="array");var d=c.type;"object"!==typeof d&&(d=[d]);for(var e=0;e<d.length;e++){var h=d[e];if(h===b||"integer"===h&&"number"===b&&0===a%1)return null}return this.createError(l.INVALID_TYPE,{type:b,expected:d.join("/")})};g.prototype.validateEnum=function(a,c){if(void 0===
c["enum"])return null;for(var b=0;b<c["enum"].length;b++)if(r(a,c["enum"][b]))return null;return this.createError(l.ENUM_MISMATCH,{value:"undefined"!==typeof JSON?JSON.stringify(a):a})};g.prototype.validateNumeric=function(a,c,b){return this.validateMultipleOf(a,c,b)||this.validateMinMax(a,c,b)||this.validateNaN(a,c,b)||null};var y=Math.pow(2,-51),q=1-y;g.prototype.validateMultipleOf=function(a,c){var b=c.multipleOf||c.divisibleBy;if(void 0===b)return null;if("number"===typeof a){var d=a/b%1;if(d>=
y&&d<q)return this.createError(l.NUMBER_MULTIPLE_OF,{value:a,multipleOf:b})}return null};g.prototype.validateMinMax=function(a,c){if("number"!==typeof a)return null;if(void 0!==c.minimum){if(a<c.minimum)return this.createError(l.NUMBER_MINIMUM,{value:a,minimum:c.minimum}).prefixWith(null,"minimum");if(c.exclusiveMinimum&&a===c.minimum)return this.createError(l.NUMBER_MINIMUM_EXCLUSIVE,{value:a,minimum:c.minimum}).prefixWith(null,"exclusiveMinimum")}if(void 0!==c.maximum){if(a>c.maximum)return this.createError(l.NUMBER_MAXIMUM,
{value:a,maximum:c.maximum}).prefixWith(null,"maximum");if(c.exclusiveMaximum&&a===c.maximum)return this.createError(l.NUMBER_MAXIMUM_EXCLUSIVE,{value:a,maximum:c.maximum}).prefixWith(null,"exclusiveMaximum")}return null};g.prototype.validateNaN=function(a){return"number"!==typeof a?null:!0===isNaN(a)||Infinity===a||-Infinity===a?this.createError(l.NUMBER_NOT_A_NUMBER,{value:a}).prefixWith(null,"type"):null};g.prototype.validateString=function(a,c,b){return this.validateStringLength(a,c,b)||this.validateStringPattern(a,
c,b)||null};g.prototype.validateStringLength=function(a,c){return"string"!==typeof a?null:void 0!==c.minLength&&a.length<c.minLength?this.createError(l.STRING_LENGTH_SHORT,{length:a.length,minimum:c.minLength}).prefixWith(null,"minLength"):void 0!==c.maxLength&&a.length>c.maxLength?this.createError(l.STRING_LENGTH_LONG,{length:a.length,maximum:c.maxLength}).prefixWith(null,"maxLength"):null};g.prototype.validateStringPattern=function(a,c){return"string"!==typeof a||void 0===c.pattern?null:(new RegExp(c.pattern)).test(a)?
null:this.createError(l.STRING_PATTERN,{pattern:c.pattern}).prefixWith(null,"pattern")};g.prototype.validateArray=function(a,c,b){return Array.isArray(a)?this.validateArrayLength(a,c,b)||this.validateArrayUniqueItems(a,c,b)||this.validateArrayItems(a,c,b)||null:null};g.prototype.validateArrayLength=function(a,c){var b;return void 0!==c.minItems&&a.length<c.minItems&&(b=this.createError(l.ARRAY_LENGTH_SHORT,{length:a.length,minimum:c.minItems}).prefixWith(null,"minItems"),this.handleError(b))||void 0!==
c.maxItems&&a.length>c.maxItems&&(b=this.createError(l.ARRAY_LENGTH_LONG,{length:a.length,maximum:c.maxItems}).prefixWith(null,"maxItems"),this.handleError(b))?b:null};g.prototype.validateArrayUniqueItems=function(a,c){if(c.uniqueItems)for(var b=0;b<a.length;b++)for(var d=b+1;d<a.length;d++)if(r(a[b],a[d])){var e=this.createError(l.ARRAY_UNIQUE,{match1:b,match2:d}).prefixWith(null,"uniqueItems");if(this.handleError(e))return e}return null};g.prototype.validateArrayItems=function(a,c,b){if(void 0===
c.items)return null;var d,e;if(Array.isArray(c.items))for(e=0;e<a.length;e++)if(e<c.items.length){if(d=this.validateAll(a[e],c.items[e],[e],["items",e],b+"/"+e))return d}else{if(void 0!==c.additionalItems)if("boolean"===typeof c.additionalItems){if(!c.additionalItems&&(d=this.createError(l.ARRAY_ADDITIONAL_ITEMS,{}).prefixWith(""+e,"additionalItems"),this.handleError(d)))return d}else if(d=this.validateAll(a[e],c.additionalItems,[e],["additionalItems"],b+"/"+e))return d}else for(e=0;e<a.length;e++)if(d=
this.validateAll(a[e],c.items,[e],["items"],b+"/"+e))return d;return null};g.prototype.validateObject=function(a,c,b){return"object"!==typeof a||null===a||Array.isArray(a)?null:this.validateObjectMinMaxProperties(a,c,b)||this.validateObjectRequiredProperties(a,c,b)||this.validateObjectProperties(a,c,b)||this.validateObjectDependencies(a,c,b)||null};g.prototype.validateObjectMinMaxProperties=function(a,c){var b=Object.keys(a),d;return void 0!==c.minProperties&&b.length<c.minProperties&&(d=this.createError(l.OBJECT_PROPERTIES_MINIMUM,
{propertyCount:b.length,minimum:c.minProperties}).prefixWith(null,"minProperties"),this.handleError(d))||void 0!==c.maxProperties&&b.length>c.maxProperties&&(d=this.createError(l.OBJECT_PROPERTIES_MAXIMUM,{propertyCount:b.length,maximum:c.maxProperties}).prefixWith(null,"maxProperties"),this.handleError(d))?d:null};g.prototype.validateObjectRequiredProperties=function(a,c){if(void 0!==c.required)for(var b=0;b<c.required.length;b++){var d=c.required[b];if(void 0===a[d]&&(d=this.createError(l.OBJECT_REQUIRED,
{key:d}).prefixWith(null,""+b).prefixWith(null,"required"),this.handleError(d)))return d}return null};g.prototype.validateObjectProperties=function(a,c,b){var d,e;for(e in a){var h=b+"/"+e.replace(/~/g,"~0").replace(/\//g,"~1"),k=!1;if(void 0!==c.properties&&void 0!==c.properties[e]&&(k=!0,d=this.validateAll(a[e],c.properties[e],[e],["properties",e],h)))return d;if(void 0!==c.patternProperties)for(var n in c.patternProperties)if((new RegExp(n)).test(e)&&(k=!0,d=this.validateAll(a[e],c.patternProperties[n],
[e],["patternProperties",n],h)))return d;if(k)this.trackUnknownProperties&&(this.knownPropertyPaths[h]=!0,delete this.unknownPropertyPaths[h]);else if(void 0!==c.additionalProperties)if(this.trackUnknownProperties&&(this.knownPropertyPaths[h]=!0,delete this.unknownPropertyPaths[h]),"boolean"===typeof c.additionalProperties){if(!c.additionalProperties&&(d=this.createError(l.OBJECT_ADDITIONAL_PROPERTIES,{}).prefixWith(e,"additionalProperties"),this.handleError(d)))return d}else{if(d=this.validateAll(a[e],
c.additionalProperties,[e],["additionalProperties"],h))return d}else this.trackUnknownProperties&&!this.knownPropertyPaths[h]&&(this.unknownPropertyPaths[h]=!0)}return null};g.prototype.validateObjectDependencies=function(a,c,b){var d;if(void 0!==c.dependencies)for(var e in c.dependencies)if(void 0!==a[e]){var h=c.dependencies[e];if("string"===typeof h){if(void 0===a[h]&&(d=this.createError(l.OBJECT_DEPENDENCY_KEY,{key:e,missing:h}).prefixWith(null,e).prefixWith(null,"dependencies"),this.handleError(d)))return d}else if(Array.isArray(h))for(var k=
0;k<h.length;k++){if(d=h[k],void 0===a[d]&&(d=this.createError(l.OBJECT_DEPENDENCY_KEY,{key:e,missing:d}).prefixWith(null,""+k).prefixWith(null,e).prefixWith(null,"dependencies"),this.handleError(d)))return d}else if(d=this.validateAll(a,h,[],["dependencies",e],b))return d}return null};g.prototype.validateCombinations=function(a,c,b){return this.validateAllOf(a,c,b)||this.validateAnyOf(a,c,b)||this.validateOneOf(a,c,b)||this.validateNot(a,c,b)||null};g.prototype.validateAllOf=function(a,c,b){if(void 0===
c.allOf)return null;for(var d,e=0;e<c.allOf.length;e++)if(d=this.validateAll(a,c.allOf[e],[],["allOf",e],b))return d;return null};g.prototype.validateAnyOf=function(a,c,b){if(void 0===c.anyOf)return null;var d=[],e=this.errors.length,h,k;this.trackUnknownProperties&&(h=this.unknownPropertyPaths,k=this.knownPropertyPaths);for(var n=!0,g=0;g<c.anyOf.length;g++){this.trackUnknownProperties&&(this.unknownPropertyPaths={},this.knownPropertyPaths={});var w=this.errors.length,m=this.validateAll(a,c.anyOf[g],
[],["anyOf",g],b);if(null===m&&w===this.errors.length){this.errors=this.errors.slice(0,e);if(this.trackUnknownProperties){for(var r in this.knownPropertyPaths)k[r]=!0,delete h[r];for(var p in this.unknownPropertyPaths)k[p]||(h[p]=!0);n=!1;continue}return null}m&&d.push(m.prefixWith(null,""+g).prefixWith(null,"anyOf"))}this.trackUnknownProperties&&(this.unknownPropertyPaths=h,this.knownPropertyPaths=k);if(n)return d=d.concat(this.errors.slice(e)),this.errors=this.errors.slice(0,e),this.createError(l.ANY_OF_MISSING,
{},"","/anyOf",d)};g.prototype.validateOneOf=function(a,c,b){if(void 0===c.oneOf)return null;var d=null,e=[],h=this.errors.length,k,n;this.trackUnknownProperties&&(k=this.unknownPropertyPaths,n=this.knownPropertyPaths);for(var g=0;g<c.oneOf.length;g++){this.trackUnknownProperties&&(this.unknownPropertyPaths={},this.knownPropertyPaths={});var w=this.errors.length,m=this.validateAll(a,c.oneOf[g],[],["oneOf",g],b);if(null===m&&w===this.errors.length){if(null===d)d=g;else return this.errors=this.errors.slice(0,
h),this.createError(l.ONE_OF_MULTIPLE,{index1:d,index2:g},"","/oneOf");if(this.trackUnknownProperties){for(var r in this.knownPropertyPaths)n[r]=!0,delete k[r];for(var p in this.unknownPropertyPaths)n[p]||(k[p]=!0)}}else m&&e.push(m)}this.trackUnknownProperties&&(this.unknownPropertyPaths=k,this.knownPropertyPaths=n);if(null===d)return e=e.concat(this.errors.slice(h)),this.errors=this.errors.slice(0,h),this.createError(l.ONE_OF_MISSING,{},"","/oneOf",e);this.errors=this.errors.slice(0,h);return null};
g.prototype.validateNot=function(a,c,b){if(void 0===c.not)return null;var d=this.errors.length,e,h;this.trackUnknownProperties&&(e=this.unknownPropertyPaths,h=this.knownPropertyPaths,this.unknownPropertyPaths={},this.knownPropertyPaths={});a=this.validateAll(a,c.not,null,null,b);c=this.errors.slice(d);this.errors=this.errors.slice(0,d);this.trackUnknownProperties&&(this.unknownPropertyPaths=e,this.knownPropertyPaths=h);return null===a&&0===c.length?this.createError(l.NOT_PASSED,{},"","/not"):null};
g.prototype.validateHypermedia=function(a,c,d){if(!c.links)return null;for(var h,k=0;k<c.links.length;k++)if(h=c.links[k],"describedby"===h.rel){h=new b(h.href);for(var g=!0,n=0;n<h.varNames.length;n++)if(!(h.varNames[n]in a)){g=!1;break}if(g&&(h={$ref:h.fillFromObject(a)},h=this.validateAll(a,h,[],["links",k],d)))return h}};var l={INVALID_TYPE:0,ENUM_MISMATCH:1,ANY_OF_MISSING:10,ONE_OF_MISSING:11,ONE_OF_MULTIPLE:12,NOT_PASSED:13,NUMBER_MULTIPLE_OF:100,NUMBER_MINIMUM:101,NUMBER_MINIMUM_EXCLUSIVE:102,
NUMBER_MAXIMUM:103,NUMBER_MAXIMUM_EXCLUSIVE:104,NUMBER_NOT_A_NUMBER:105,STRING_LENGTH_SHORT:200,STRING_LENGTH_LONG:201,STRING_PATTERN:202,OBJECT_PROPERTIES_MINIMUM:300,OBJECT_PROPERTIES_MAXIMUM:301,OBJECT_REQUIRED:302,OBJECT_ADDITIONAL_PROPERTIES:303,OBJECT_DEPENDENCY_KEY:304,ARRAY_LENGTH_SHORT:400,ARRAY_LENGTH_LONG:401,ARRAY_UNIQUE:402,ARRAY_ADDITIONAL_ITEMS:403,FORMAT_CUSTOM:500,KEYWORD_CUSTOM:501,CIRCULAR_REFERENCE:600,UNKNOWN_PROPERTY:1E3},A={},E;for(E in l)A[l[E]]=E;var v={INVALID_TYPE:"Invalid type: {type} (expected {expected})",
ENUM_MISMATCH:"No enum match for: {value}",ANY_OF_MISSING:'Data does not match any schemas from "anyOf"',ONE_OF_MISSING:'Data does not match any schemas from "oneOf"',ONE_OF_MULTIPLE:'Data is valid against more than one schema from "oneOf": indices {index1} and {index2}',NOT_PASSED:'Data matches schema from "not"',NUMBER_MULTIPLE_OF:"Value {value} is not a multiple of {multipleOf}",NUMBER_MINIMUM:"Value {value} is less than minimum {minimum}",NUMBER_MINIMUM_EXCLUSIVE:"Value {value} is equal to exclusive minimum {minimum}",
NUMBER_MAXIMUM:"Value {value} is greater than maximum {maximum}",NUMBER_MAXIMUM_EXCLUSIVE:"Value {value} is equal to exclusive maximum {maximum}",NUMBER_NOT_A_NUMBER:"Value {value} is not a valid number",STRING_LENGTH_SHORT:"String is too short ({length} chars), minimum {minimum}",STRING_LENGTH_LONG:"String is too long ({length} chars), maximum {maximum}",STRING_PATTERN:"String does not match pattern: {pattern}",OBJECT_PROPERTIES_MINIMUM:"Too few properties defined ({propertyCount}), minimum {minimum}",
OBJECT_PROPERTIES_MAXIMUM:"Too many properties defined ({propertyCount}), maximum {maximum}",OBJECT_REQUIRED:"Missing required property: {key}",OBJECT_ADDITIONAL_PROPERTIES:"Additional properties not allowed",OBJECT_DEPENDENCY_KEY:"Dependency failed - key must exist: {missing} (due to key: {key})",ARRAY_LENGTH_SHORT:"Array is too short ({length}), minimum {minimum}",ARRAY_LENGTH_LONG:"Array is too long ({length}), maximum {maximum}",ARRAY_UNIQUE:"Array items are not unique (indices {match1} and {match2})",
ARRAY_ADDITIONAL_ITEMS:"Additional items not allowed",FORMAT_CUSTOM:"Format validation failed ({message})",KEYWORD_CUSTOM:"Keyword failed: {key} ({message})",CIRCULAR_REFERENCE:"Circular $refs: {urls}",UNKNOWN_PROPERTY:"Unknown property (not in schema)"};k.prototype=Object.create(Error.prototype);k.prototype.constructor=k;k.prototype.name="ValidationError";k.prototype.prefixWith=function(a,c){null!==a&&(a=a.replace(/~/g,"~0").replace(/\//g,"~1"),this.dataPath="/"+a+this.dataPath);null!==c&&(c=c.replace(/~/g,
"~0").replace(/\//g,"~1"),this.schemaPath="/"+c+this.schemaPath);if(null!==this.subErrors)for(var b=0;b<this.subErrors.length;b++)this.subErrors[b].prefixWith(a,c);return this};var u={};E=p();E.addLanguage("en-us",v);return E.tv4=E},L=L?L:new function(){function a(a,b){I({url:a,async:!1,cache:b.cache,contentType:"text/plain;charset="+b.encoding,dataType:"text",success:function(a,e){d(a,b.mode)}})}function d(a,b){for(var d="",k=a.split(/\n/),p=/(\{\d+\})/g,K=/\{(\d+)\}/g,x=/(\\u.{4})/ig,g=0;g<k.length;g++)if(k[g]=
k[g].replace(/^\s\s*/,"").replace(/\s\s*$/,""),0<k[g].length&&"#"!=k[g].match("^#")){var y=k[g].split("=");if(0<y.length){for(var q=unescape(y[0]).replace(/^\s\s*/,"").replace(/\s\s*$/,""),l=1==y.length?"":y[1];"\\"==l.match(/\\$/);)l=l.substring(0,l.length-1),l+=k[++g].replace(/\s\s*$/,"");for(var A=2;A<y.length;A++)l+="="+y[A];l=l.replace(/^\s\s*/,"").replace(/\s\s*$/,"");if("map"==b||"both"==b){if(y=l.match(x))for(A=0;A<y.length;A++)l=l.replace(y[A],r(y[A]));m.map[q]=l}if("vars"==b||"both"==b)if(l=
l.replace(/"/g,'\\"'),e(q),p.test(l)){for(var y=l.split(p),A=!0,v="",C=[],u=0;u<y.length;u++)!p.test(y[u])||0!==C.length&&-1!==C.indexOf(y[u])||(A||(v+=","),v+=y[u].replace(K,"v$1"),C.push(y[u]),A=!1);d+=q+"=function("+v+"){";q='"'+l.replace(K,'"+v$1+"')+'"';d+="return "+q+";};"}else d+=q+'="'+l+'";'}}eval(d)}function e(a){if(/\./.test(a)){var b="";a=a.split(/\./);for(var d=0;d<a.length;d++)0<d&&(b+="."),b+=a[d],eval("typeof "+b+' == "undefined"')&&eval(b+"={};")}}function r(a){var b=[];a=parseInt(a.substr(2),
16);0<=a&&a<Math.pow(2,16)&&b.push(a);a="";for(var d=0;d<b.length;++d)a+=String.fromCharCode(b[d]);return a}var m={map:{}};this.properties=function(d){d=b.Utility.extend({name:b.Configuration.MessageBundle,language:"",path:"",mode:"vars",cache:!1,encoding:"UTF-8",callback:null},d);if(null===d.language||""===d.language){var e=d,m=navigator.language||navigator.userLanguage,m=m.toLowerCase();3<m.length&&(m=m.substring(0,3)+m.substring(3).toUpperCase());e.language=m}null===d.language&&(d.language="");
e=(e=d.name)&&e.constructor==Array?e:[e];for(m=0;m<e.length;m++)a(d.path+e[m]+".properties",d),2<=d.language.length&&a(d.path+e[m]+"_"+d.language.substring(0,2)+".properties",d),5<=d.language.length&&a(d.path+e[m]+"_"+d.language.substring(0,5)+".properties",d);d.callback&&d.callback()};this.prop=function(a){var b=m.map[a];if(!b)return"["+a+"]";var d;2==arguments.length&&Array.isArray(arguments[1])&&(d=arguments[1]);var e;if("string"==typeof b){for(e=0;-1!=(e=b.indexOf("\\",e));)b="t"==b.charAt(e+
1)?b.substring(0,e)+"\t"+b.substring(e++ +2):"r"==b.charAt(e+1)?b.substring(0,e)+"\r"+b.substring(e++ +2):"n"==b.charAt(e+1)?b.substring(0,e)+"\n"+b.substring(e++ +2):"f"==b.charAt(e+1)?b.substring(0,e)+"\f"+b.substring(e++ +2):"\\"==b.charAt(e+1)?b.substring(0,e)+"\\"+b.substring(e++ +2):b.substring(0,e)+b.substring(e+1);var r=[],p,q;for(e=0;e<b.length;)if("'"==b.charAt(e))if(e==b.length-1)b=b.substring(0,e);else if("'"==b.charAt(e+1))b=b.substring(0,e)+b.substring(++e);else{for(p=e+2;-1!=(p=b.indexOf("'",
p));)if(p==b.length-1||"'"!=b.charAt(p+1)){b=b.substring(0,e)+b.substring(e+1,p)+b.substring(p+1);e=p-1;break}else b=b.substring(0,p)+b.substring(++p);-1==p&&(b=b.substring(0,e)+b.substring(e+1))}else if("{"==b.charAt(e))if(p=b.indexOf("}",e+1),-1==p)e++;else if(q=parseInt(b.substring(e+1,p)),!isNaN(q)&&0<=q){var g=b.substring(0,e);""!==g&&r.push(g);r.push(q);e=0;b=b.substring(p+1)}else e=p+1;else e++;""!==b&&r.push(b);b=r;m.map[a]=r}if(0===b.length)return"";if(1==b.lengh&&"string"==typeof b[0])return b[0];
g="";for(e=0;e<b.length;e++)g="string"==typeof b[e]?g+b[e]:d&&b[e]<d.length?g+d[b[e]]:!d&&b[e]+1<arguments.length?g+arguments[b[e]+1]:g+("{"+b[e]+"}");return g}};b.Utility.BundleObject={name:"",mode:"both",cache:!0};b.Utility.ResourceBundle={getBundle:function(){return L.properties.apply(this,arguments)},getString:function(){return L.prop.apply(this,arguments)}};b.Utility.MessageReader={getMessage:function(a){for(var d=b.Utility.ResourceBundle.getString.apply(this,arguments),e=a.length,p=a;0<e&&d==
"["+a+"]";)e=a.lastIndexOf("."),a=a.substring(0,e),d=b.Utility.ResourceBundle.getString.apply(this,arguments);return a?d:"["+p+"]"}};b.Utility.MessageKeyFormatter={delimiter:".",format:function(a){var b="";a&&a.level&&(b+=a.level,a.kind&&(b+=this.delimiter+a.kind,a.rule&&(b+=this.delimiter+a.rule,a.values.title&&(b+=this.delimiter+a.values.title))));return b?b:""}};b.ValidationFramework=b.ValidationFramework?b.ValidationFramework:new function(){var a;void 0===a&&(a=new V);this.supportsValidation=
function(){return null!==a};this.registerSchema=function(b,e){a.addSchema(b,e)};this.getSchema=function(b){return a.getSchema(b)};this.getSchemas=function(){return a.getSchemaMap()};this.clearSchemas=function(){a.dropSchemas()};this.validate=function(b,e){return a.validateMultiple(b,e)};this.getValidationMessages=function(){return a.error}};D=x.Model.extend({schema:null,mock:!1,validationMessages:{valid:!0},supportsValidation:function(){return null!==this.schema?!0:!1},isValid:function(){this.validate();
return this.validationMessages.valid},validate:function(){this.supportsValidation()&&b.ValidationFramework.supportsValidation()?this.validationMessages=b.ValidationFramework.validate(this.toJSON(),this.schema):this.validationMessages.valid=!0;return this.validationMessages},crossOrigin:!1,sync:function(a,d,e){e||(e={});!0===this.crossOrigin&&(e.crossDomain=!0);e.xhrFields||(e.xhrFields={withCredentials:!0});this.mock&&(e.mock=this.mock);return b.sync(a,d,e)}});b.Utility.extend(D,b.Object);var O=x.Collection.extend({schema:null,
mock:!1,validationMessages:{valid:!0},supportsValidation:function(){return null!==this.schema?!0:!1},isValid:function(){this.validate();return this.validationMessages.valid},validate:function(){this.supportsValidation()&&b.ValidationFramework.supportsValidation()?this.validationMessages=b.ValidationFramework.validate(this.toJSON(),this.schema):this.validationMessages.valid=!0;return this.validationMessages},crossOrigin:!1,sync:function(a,d,e){e||(e={});!0===this.crossOrigin&&(e.crossDomain=!0);e.xhrFields||
(e.xhrFields={withCredentials:!0});this.mock&&(e.mock=this.mock);return b.sync(a,d,e)}});b.Utility.extend(O,b.Object);var P=b.PaginatedCollection=O.extend({paginationConfiguration:{currentPageParam:"page",pageSizeParam:"per_page"},pageSize:20,currentPage:1,totalPages:1,setPageSize:function(a){a&&(this.pageSize=a);this.refresh()},setCurrentPage:function(a){a||(a=1);this.currentPage=a;this.refresh()},setPaginationConfiguration:function(a){this.paginationConfiguration=a},fetch:function(a){a=a?a:{};var d=
this.paginationConfiguration,e={};e[d.currentPageParam]=this.currentPage;e[d.pageSizeParam]=this.pageSize;a.data=e;return b.Collection.prototype.fetch.call(this,a)},nextPage:function(){this.currentPage<this.totalPages&&(this.currentPage+=1,this.refresh())},previousPage:function(){0<this.currentPage&&(--this.currentPage,this.refresh())},goToPage:function(a){a&&a<this.totalPages&&0<a&&(this.currentPage=a,this.refresh())},firstPage:function(){this.currentPage=1;this.refresh()},lastPage:function(){this.currentPage=
this.totalPages;this.refresh()},refresh:function(){this.fetch()}}),H={github:"github",solr:"solr",database:"database"};b.PaginationFactory={type:H,getPaginatedCollection:function(a,b){var e=b?b:{},p=null;a||(a=H.github);a===H.github?(p=new P(e),p.setPaginationConfiguration({currentPageParam:"page",pageSizeParam:"per_page"})):a===H.solr?(p=new P(e),p.setPaginationConfiguration({currentPageParam:"start",pageSizeParam:"rows"})):a===H.database&&(p=new P(e),p.setPaginationConfiguration({currentPageParam:"offset",
pageSizeParam:"limit"}));return p}};var R=x.View.extend({init:function(a){},initialize:function(a){this.init(a);this.render=b.Utility.wrap(this.render,function(a){this.beforeRender();a();this.afterRender();return this})},beforeRender:function(){},render:function(){return this},afterRender:function(){},name:"",setName:function(a){this.name=a},getName:function(){return this.name},permissions:{include:[],exclude:[]},addPermission:function(a,b){b||(b=!1);null===a||Array.isArray(a)||(b?this.permissions.exclude:
this.permissions.include).push(a)},removePermission:function(a,b){b||(b=!1);if(null!==a&&!Array.isArray(a)){var e=b?this.permissions.exclude:this.permissions.include;e.splice(e.indexOf(a),1)}},setPermissions:function(a,b){b||(b=!1);null!==a&&Array.isArray(a)&&(b?this.permissions.exclude=a:this.permissions.include=a)},getPermissions:function(){return this.permissions},clearPermissions:function(){this.permissions={include:[],exclude:[]}},matchesPermission:function(a,b){b||(b=!1);return-1!==(b?this.permissions.exclude:
this.permissions.include).indexOf(a)},canDisplay:function(){return!0}});b.Utility.extend(R,b.Object);b.Model=D;b.Collection=O;b.View=R;b.history=x.history;b.History=x.History;b.Router=x.Router;var W=function(a){this.isPersisted=a;this.myStore=null;this.isSupported=function(){return"undefined"!==typeof Storage};this.isSupported()?(C.debug("localStorage exists"),this.myStore=this.isPersisted?localStorage:sessionStorage):C.debug("No localStorage.");this.getItem=function(a){return(a=this.myStore.getItem(a))?
JSON.parse(a):null};this.setItem=function(a,b){this.myStore.setItem(a,JSON.stringify(b))};this.removeItem=function(a){this.myStore.removeItem(a)};this.clear=function(){this.myStore.clear()};this.key=function(a){return this.myStore.key(a)};this.length=function(){return this.myStore.length}},Y=function(a,d){var e=X.getStorage(a);this.myNameSpacedStore=new b.Utility.AugmentedMap;this.namespace=d;this.isSupported=function(){return e&&e.isSupported()};this.isSupported()&&this.namespace&&e.setItem(this.namespace,
JSON.stringify(this.myNameSpacedStore.toJSON()));this.getItem=function(a){var b={};try{b=JSON.parse(e.getItem(this.namespace))}catch(d){return C.error("Could not parse item map from storage!"),null}this.myNameSpacedStore.clear();this.myNameSpacedStore.marshall(b);if(a=this.myNameSpacedStore.get(a)){var n;try{n=JSON.parse(a)}catch(d){n=a}return n}return null};this.setItem=function(a,m){this.myNameSpacedStore||(this.myNameSpacedStore=new b.Utility.AugmentedMap);this.myNameSpacedStore.set(a,m);e.setItem(d,
JSON.stringify(this.myNameSpacedStore.toJSON()))};this.removeItem=function(a){this.getItem(a);this.myNameSpacedStore.remove(a);e.setItem(d,JSON.stringify(this.myNameSpacedStore.toJSON()))};this.clear=function(){this.myNameSpacedStore.clear();e.setItem(d,JSON.stringify(this.myNameSpacedStore.toJSON()))};this.key=function(a){return this.myNameSpacedStore.key(a)};this.length=function(){return this.myNameSpacedStore.size()}},X=b.LocalStorageFactory={getStorage:function(a,b){var e=null;return(e=b?new Y(a,
b):new W(a))&&e.isSupported()?e:null}};b.Utility.Stack=function(){this.stack=[];this.empty=function(){return 0===this.stack.length};this.peek=function(){return this.stack[0]};this.pop=function(){return this.stack.pop()};this.push=function(a){this.stack.push(a)};this.search=function(a){return this.stack.indexOf(a)};this.size=function(){return this.stack.length};this.clear=function(){this.stack.splice(0,this.stack.length)};this.toArray=function(){return this.stack}};b.Utility.AsynchronousQueue=function(a){var d=
a?a:b.Configuration.AsynchronousQueueTimeout;this.queue={};this.add=function(){var a=arguments;if(0>=a.length)return!1;b.Utility.extend(this.queue,a)};this.clear=function(){0<this.queue.length&&this.queue.splice(0,this.queue.length)};this.process=function(){arguments&&b.Utility.extend(this.queue,arguments);var a=this.queue;if(0>=a.length)return!1;(function m(b){if(b>=a.length||"function"!==typeof a[b])return!1;window.setTimeout(function(){a[b]();m(b+1)},d)})(0);return!0};this.getTimeout=function(){return d};
this.getQueue=function(){return this.queue}};D=b.Application=function(a){var d;this.started=!1;d?d.clear():d=new b.Utility.AugmentedMap;a?d.set("name",a):d.set("name","untitled");this.initialize=function(){};this.beforeInitialize=function(){};this.afterInitialize=function(){};this.getName=function(){return this.getMetadataItem("name")};this.setName=function(a){return this.setMetadataItem("name",a)};this.getMetadata=function(){return d};this.setMetadataItem=function(a,b){d.set(a,b)};this.getMetadataItem=
function(a){return d.get(a)};this.start=function(){(this.started=(new b.Utility.AsynchronousQueue(b.Configuration.ApplicationInitProcessTimeout)).process(this.beforeInitialize(),this.initialize(),this.afterInitialize(),function(){b.history.started||b.history.start()}))||this.stop()};this.stop=function(){b.history.started&&b.history.stop();this.started=!1}};b.Application.prototype.constructor=D;return b});