/*
 Apache-2.0
*/
(function(E,c){"function"===typeof define&&define.amd?define(["backbone","exports"],function(v,w){E.Augmented=c(E,w,v)}):"undefined"!==typeof exports?(require("backbone"),c(E,exports,Backbone)):E.Augmented=c(E,{},E.Backbone)})(this,function(E,c,v){var w=function(){for(var a=0,b=arguments.length,a=1;a<b;a++)for(var e in arguments[a])arguments[a].hasOwnProperty(e)&&(arguments[0][e]=arguments[a][e]);return arguments[0]};w(c,v);var Q=E.Augmented;c.VERSION="0.2.0";c.codename="Adam Jensen";c.releasename=
"Hengsha";c.noConflict=function(){E.Augmented=Q;v.noConflict();return this};c._=v._;c.$=v.$;c.Configuration={LoggerLevel:"debug",MessageBundle:"Messages",AsynchronousQueueTimeout:2E3,ApplicationInitProcessTimeout:1E3};c.extend=v.Model.extend;c.sync=v.sync;c.isFunction=function(a){return"[object Function]"==Object.prototype.toString.call(a)};c.result=function(a,b){if(null!==a){var e=a[b];return c.isFunction(e)?e.call(a):e}};Array.prototype.includes||(Array.prototype.includes=function(a,b){var e=Object(this),
c=parseInt(e.length)||0;if(0===c)return!1;var r=parseInt(b)||0;0<=r||(r=c+r,0>r&&(r=0));for(var q;r<c;){q=e[r];if(a===q||a!==a&&q!==q)return!0;r++}return!1});Array.prototype.has=function(a){return-1!==this.indexOf(a)};c.Utility={};c.Utility.Sort=function(a,b){return a.sort(function(a,c){var r=a[b],q=c[b];return r<q?-1:r>q?1:0})};var u=c.Utility.TransformerType={xString:0,xInteger:1,xNumber:2,xBoolean:3,xArray:4,xObject:5,xNull:6};c.Utility.Transformer={type:u,transform:function(a,b){var e=null;switch(b){case u.xString:e=
"object"===typeof a?JSON.stringify(a):String(a);break;case u.xInteger:e=parseInt(a);break;case u.xNumber:e=Number(a);break;case u.xBoolean:e=Boolean(a);break;case u.xArray:Array.isArray(a)?e=a:(e=[],e[0]=a);break;case u.xObject:"object"!==typeof a?(e={},e[a]=a):e=a}return e},isType:function(a){if(null===a)return u.xNull;if("string"===typeof a)return u.xString;if("number"===typeof a)return u.xNumber;if("boolean"===typeof a)return u.xBoolean;if(Array.isArray(a))return u.xArray;if("object"===typeof a)return u.xObject}};
c.Utility.isString=function(a){return"string"===typeof a||!!a&&"object"===typeof a&&"[object String]"===Object.prototype.toString.call(a)};c.Utility.extend=w;var P=XMLHttpRequest;c.Utility.extend(P,{done:function(){},fail:function(){},always:function(){},then:function(){}});var R=function(){this.responseType="text";this.responseText="";this.async=!0;this.status=200;this.header={};this.timeout=70;this.open=function(a,b,e,c,r){this.url=b;this.async=e;this.user=c;this.method=a};this.send=function(){this.onload()};
this.setRequestHeader=function(a,b){this.header.header=b};this.done=function(){};this.fail=function(){};this.always=function(){};this.then=function(){};this.options={}};c.Ajax={};c.Ajax.Configuration={url:"localhost",contentType:"text/plain",dataType:"text",async:!0};var I=c.ajax=c.Ajax.ajax=function(a){C.debug("AUGMENTED: Ajax object: "+JSON.stringify(a));var b=null;if(a&&a.url){var e=a.method?a.method:"GET",c=a.cache?a.cache:!0,b=a.mock?new R:new P;a.timeout&&(b.timeout=a.timeout);var r=void 0!==
a.async?a.async:!0;a.crossDomain&&a.xhrFields&&a.xhrFields.withCredentials&&(b.withCredentials=a.xhrFields.withCredentials,r||C.warn("AUGMENTED: Augmented.ajax: Sync Not supported for all browsers in CORS mode!"),r=!0);r&&a.dataType&&(b.responseType=a.dataType?a.dataType:"text");b.open(e,encodeURI(a.url),r,void 0!==a.user?a.user:"",void 0!==a.password?a.password:"");b.setRequestHeader("Content-Type",a.contentType?a.contentType:"text/plain");c||b.setRequestHeader("Cache-Control","no-cache");b.withCredentials&&
(e="*",c="GET",a.allowOrigins&&(e=a.allowOrigins),a.allowMethods&&(c=a.allowMethods),b.setRequestHeader("Access-Control-Allow-Origin",e),b.setRequestHeader("Access-Control-Allow-Methods",c));b.withCredentials&&a.user&&a.password&&b.setRequestHeader("Authorization","Basic "+window.btoa(a.user+":"+a.password));b.onload=function(){199<b.status&&300>b.status?a.success&&(""===b.responseType||"text"===b.responseType||"json"===b.responseType&&!b.response?a.success(b.responseText,b.status,b):"json"===b.responseType?
b.response?(C.debug("AUGMENTED: Ajax (JSON responseType) native JSON."),a.success(b.response,b.status,b)):(C.debug("AUGMENTED: Ajax (JSON responseType) parsed JSON from string."),a.success(JSON.parse(b.responseText),b.status,b)):a.success(b.response,b.status,b)):399<b.status&&600>b.status&&(a.failure?a.failure(b,b.status,b.statusText):a.error&&a.error(b,b.status,b.statusText));a.complete&&a.complete(b,b.status);return b};a.beforeSend&&a.beforeSend(b);b.send()}this.done=function(){};this.fail=function(){};
this.always=function(){};this.then=function(){};return this};v.ajax=I;c.Logger={};var L=c.Logger.Type={console:"console",rest:"rest"},p=c.Logger.Level={info:"info",debug:"debug",error:"error",warn:"warn"},J=function(a){this.TIME_SEPERATOR=":";this.DATE_SEPERATOR="-";this.OPEN_GROUP=" [ ";this.CLOSE_GROUP=" ] ";this.label=p;this.loggerLevel=a?a:p.info;this.getLogTime=function(){var a=new Date;return a.getFullYear()+this.DATE_SEPERATOR+(a.getMonth()+1)+this.DATE_SEPERATOR+a.getDate()+" "+a.getHours()+
this.TIME_SEPERATOR+a.getMinutes()+this.TIME_SEPERATOR+a.getSeconds()+this.TIME_SEPERATOR+a.getMilliseconds()};this.log=function(a,e){a&&(e||(e=p.info),this.loggerLevel===p.debug&&e===p.debug?this.logMe(this.getLogTime()+this.OPEN_GROUP+p.debug+this.CLOSE_GROUP+a,e):e===p.error?this.logMe(this.getLogTime()+this.OPEN_GROUP+p.error+this.CLOSE_GROUP+a,e):e===p.warn?this.logMe(this.getLogTime()+this.OPEN_GROUP+p.warn+this.CLOSE_GROUP+a,e):this.loggerLevel!==p.debug&&this.loggerLevel!==p.info||this.logMe(this.getLogTime()+
this.OPEN_GROUP+p.info+this.CLOSE_GROUP+a,e))};this.info=function(a){this.log(a,p.info)};this.error=function(a){this.log(a,p.error)};this.debug=function(a){this.log(a,p.debug)};this.warn=function(a){this.log(a,p.warn)}},G=function(){J.apply(this,arguments)};G.prototype=Object.create(J.prototype);G.prototype.constructor=G;G.prototype.logMe=function(a,b){b===p.info?console.info(a):b===p.error?console.error(a):b===p.debug?console.log(a):b===p.warn?console.warn(a):console.log(a)};var F=function(){J.apply(this,
arguments)};F.prototype=Object.create(J.prototype);F.prototype.constructor=F;F.prototype.setURI=function(a){this.uri=a};F.prototype.logMe=function(a){I({url:this.uri,method:"POST",contentType:"text/plain",dataType:"text",async:!0,data:a,success:function(a,e){this.success()},failure:function(a,e){this.failure()}})};c.Logger.LoggerFactory={getLogger:function(a,b){if(a===L.console)return new G(b);if(a===L.rest)return new F(b)}};var C=c.Logger.LoggerFactory.getLogger(L.console,c.Configuration.LoggerLevel);
c.Utility.wrap=function(a,b){return function(){return b.apply(this,[a].concat(Array.prototype.slice.call(arguments)))}};c.Utility.Array=function(a){this.has=function(b){return a.has(b)}};c.Utility.AugmentedMap=function(a){this.keys=[];this.data={};this.set=function(a,e){null!==a&&null!==e&&(this.data[a]||this.keys.push(a),this.data[a]=e)};this.get=function(a){return this.data[a]};this.indexOf=function(a){return this.keys.indexOf(a)};this.remove=function(a){var e=this.indexOf(a);this.keys.splice(e,
1);delete this.data[a]};this.has=function(a){return-1!==this.indexOf(a)};this.forEach=function(a){if("function"===typeof a)for(var e=this.keys.length,c=0,r,c=0;c<e;c++)r=this.keys[c],a(r,this.data[r],c)};this.key=function(a){return this.keys[a]};this.entries=function(){for(var a=this.keys.length,e=Array(a),c=0;c<a;c++)e[c]={key:this.keys[c],value:this.data[c]};return e};this.values=function(){for(var a=this.keys.length,e=Array(a),c=0;c<a;c++)e[c]=this.data[c];return e};this.clear=function(){this.keys=
[];this.data={}};this.size=function(){return this.keys.length};this.toJSON=function(){return this.data};this.toString=function(){return JSON.stringify(this.data)};this.isEmpty=function(){return 0===this.keys.length};this.marshall=function(a){if(a&&a instanceof c.Utility.AugmentedMap)a=a.toJSON();else if(!(a&&a instanceof Object&&0<Object.keys(a).length))return C.warn("AUGMENTED: AugmentedMap: Could not marshall data: "+JSON.stringify(a)),!1;for(var e=Object.keys(a),n=e.length,r=0,r=0;r<n;r++){var q=
e[r];this.set(q,a[q])}return!0};if(a)return this.marshall(a)};c.Object=function(a){this.options=c.Utility.extend({},c.result(this,"options"),a);this.initialize.apply(this,arguments)};c.Object.extend=c.extend;c.Utility.extend(c.Object.prototype,v.Events,{initialize:function(){}});c.Security={};c.Security.Client={};var S=c.Security.Principal={fullName:"",id:0,login:"",email:""},T=c.Security.Context=function(a,b){this.principal=a?a:(new a).login="guest";this.permissions=b?b:[];this.getPrincipal=function(){return this.principal};
this.getPermissions=function(){return this.permissions};this.setPermissions=function(a){this.permissions=a};this.addPermission=function(a){this.permissions.push(a)};this.removePermission=function(a){a=this.permissions.indexOf(a);this.permissions.splice(a,1)};this.hasPermission=function(a){return-1!=this.permissions.indexOf(a)}};c.Security.ClientType={OAUTH2:0,ACL:1};w=c.Object.extend({type:null,uri:""});c.Security.Client.OAUTH2Client=w.extend({type:c.Security.ClientType.OAUTH2,accessToken:"",authorizationToken:"",
authorize:function(a){this.authorizationToken=""},access:function(a){this.accessToken=""}});c.Security.Client.ACLClient=w.extend({type:c.Security.ClientType.ACL,authenticate:function(a,b){var c=null;I({url:this.uri,method:"GET",user:a,password:b,success:function(a,b){var q=new S({fullName:a.fullName,id:a.id,login:a.login,email:a.email});c=new T(q,a.permissions)},failure:function(a,b){throw Error("Failed to authenticate with response of - "+b);}});return c}});c.Security.AuthenticationFactory={getSecurityClient:function(a){return a===
c.Security.ClientType.OAUTH2?new c.Security.Client.OAUTH2Client:a===c.Security.ClientType.ACL?new c.Security.Client.ACLClient:null}};c.Security.Entry=function(a,b){this.permissions=a?a:[];this.isNegative=b?b:!1;this.getPermissions=function(){return this.permissions};this.setPermissions=function(a){this.permissions=a};this.addPermission=function(a){this.permissions.push(a)};this.removePermission=function(a){a=this.permissions.indexOf(a);this.permissions.splice(a,1)};this.hasPermission=function(a){return-1!=
this.permissions.indexOf(a)};this.setNegative=function(a){this.isNegative=a}};var U=function(){function a(a){return encodeURI(a).replace(/%25[0-9][0-9]/g,function(a){return"%"+a.substring(3)})}function b(m){var d="";D[m.charAt(0)]&&(d=m.charAt(0),m=m.substring(1));var B="",y="",b=!0,c=!1,e=!1;"+"===d?b=!1:"."===d?B=y=".":"/"===d?B=y="/":"#"===d?(y="#",b=!1):";"===d?(B=y=";",e=c=!0):"?"===d?(y="?",B="&",c=!0):"&"===d&&(B=y="&",c=!0);d=[];m=m.split(",");for(var h=[],g=0,q=m.length,g=0;g<q;g++){var f=
m[g],k=null;-1!==f.indexOf(":")&&(k=f.split(":"),f=k[0],k=parseInt(k[1],10));for(var l={};v[f.charAt(f.length-1)];)l[f.charAt(f.length-1)]=!0,f=f.substring(0,f.length-1);h.push({truncate:k,name:f,suffices:l});d.push(f)}m=function(m){for(var d="",f=0,g=0,q=h.length,g=0;g<q;g++){var k=h[g],l=m(k.name);if(null===l||void 0===l||Array.isArray(l)&&0===l.length||"object"===typeof l&&0===Object.keys(l).length)f++;else if(d=g===f?d+y:d+(B||","),Array.isArray(l)){c&&(d+=k.name+"=");for(var n=0,q=l.length,n=
0;n<q;n++)0<n&&(d+=k.suffices["*"]?B||",":",",k.suffices["*"]&&c&&(d+=k.name+"=")),d+=b?encodeURIComponent(l[n]).replace(/!/g,"%21"):a(l[n])}else if("object"===typeof l){c&&!k.suffices["*"]&&(d+=k.name+"=");var n=!0,r;for(r in l)n||(d+=k.suffices["*"]?B||",":","),n=!1,d+=b?encodeURIComponent(r).replace(/!/g,"%21"):a(r),d+=k.suffices["*"]?"=":",",d+=b?encodeURIComponent(l[r]).replace(/!/g,"%21"):a(l[r])}else c&&(d+=k.name,e&&""===l||(d+="=")),null!==k.truncate&&(l=l.substring(0,k.truncate)),d+=b?encodeURIComponent(l).replace(/!/g,
"%21"):a(l)}return d};m.varNames=d;return{prefix:y,substitution:m}}function c(a){if(!(this instanceof c))return new c(a);for(var d=a.split("{"),B=[d.shift()],y=[],M=[],h=[];0<d.length;){var g=d.shift(),f=g.split("}")[0],g=g.substring(f.length+1),f=b(f);M.push(f.substitution);y.push(f.prefix);B.push(g);h=h.concat(f.substitution.varNames)}this.fill=function(a){for(var m=B[0],d=0,y=M.length,d=0;d<y;d++)m+=(0,M[d])(a),m+=B[d+1];return m};this.varNames=h;this.template=a}function n(a,d){if(a===d)return!0;
if("object"===typeof a&&"object"===typeof d){if(Array.isArray(a)!==Array.isArray(d))return!1;if(Array.isArray(a)){if(a.length!==d.length)return!1;for(var b=0,y=a.length,b=0;b<y;b++)if(!n(a[b],d[b]))return!1}else{for(b in a)if(void 0===d[b]&&void 0!==a[b])return!1;for(b in d)if(void 0===a[b]&&void 0!==d[b])return!1;for(b in a)if(!n(a[b],d[b]))return!1}return!0}return!1}function r(a){return(a=String(a).replace(/^\s+|\s+$/g,"").match(/^([^:\/?#]+:)?(\/\/(?:[^:@]*(?::[^:@]*)?@)?(([^:\/?#]*)(?::(\d*))?))?([^?#]*)(\?[^#]*)?(#[\s\S]*)?/))?
{href:a[0]||"",protocol:a[1]||"",authority:a[2]||"",host:a[3]||"",hostname:a[4]||"",port:a[5]||"",pathname:a[6]||"",search:a[7]||"",hash:a[8]||""}:null}function q(a,d){function b(a){var d=[];a.replace(/^(\.\.?(\/|$))+/,"").replace(/\/(\.(\/|$))+/g,"/").replace(/\/\.\.$/,"/../").replace(/\/?[^\/]*/g,function(a){"/.."===a?d.pop():d.push(a)});return d.join("").replace(/^\//,"/"===a.charAt(0)?"/":"")}d=r(d||"");a=r(a||"");return d&&a?(d.protocol||a.protocol)+(d.protocol||d.authority?d.authority:a.authority)+
b(d.protocol||d.authority||"/"===d.pathname.charAt(0)?d.pathname:d.pathname?(a.authority&&!a.pathname?"/":"")+a.pathname.slice(0,a.pathname.lastIndexOf("/")+1)+d.pathname:a.pathname)+(d.protocol||d.authority||d.pathname?d.search:d.search||a.search)+d.hash:null}function h(a){return a.split("#")[0]}function l(a,d){if(a&&"object"===typeof a)if(void 0===d?d=a.id:"string"===typeof a.id&&(d=q(d,a.id),a.id=d),Array.isArray(a))for(var b=0,y=a.length,b=0;b<y;b++)l(a[b],d);else for(b in"string"===typeof a.$ref&&
(a.$ref=q(d,a.$ref)),a)"enum"!==b&&l(a[b],d)}function g(a,d,b,y,c,e){Error.call(this);if(void 0===a)throw Error("No code supplied for error: "+d);this.message=d;this.params=b;this.code=a;this.dataPath=y||"";this.schemaPath=c||"";this.subErrors=e||null;a=Error(this.message);this.stack=a.stack||a.stacktrace;if(!this.stack)try{throw a;}catch(h){this.stack=h.stack||h.stacktrace}}function p(a){var d=new f,b=a||"en";return{addFormat:function(){d.addFormat.apply(d,arguments)},language:function(a){if(!a)return b;
z[a]||(a=a.split("-")[0]);return z[a]?b=a:!1},addLanguage:function(a,d){for(var m in k)d[m]&&!d[k[m]]&&(d[k[m]]=d[m]);var b=a.split("-")[0];if(z[b])for(m in z[a]=Object.create(z[b]),d)"undefined"===typeof z[b][m]&&(z[b][m]=d[m]),z[a][m]=d[m];else z[a]=d,z[b]=d;return this},freshApi:function(a){var d=p();a&&d.language(a);return d},validate:function(a,m,c,e){c=new f(d,!1,z[b],c,e);"string"===typeof m&&(m={$ref:m});c.addSchema("",m);a=c.validateAll(a,m,null,null,"");!a&&e&&(a=c.banUnknownProperties());
this.error=a;this.missing=c.missing;return this.valid=null===a},validateResult:function(){var a={};this.validate.apply(a,arguments);return a},validateMultiple:function(a,m,c,e){c=new f(d,!0,z[b],c,e);"string"===typeof m&&(m={$ref:m});c.addSchema("",m);c.validateAll(a,m,null,null,"");e&&c.banUnknownProperties();a={};a.errors=c.errors;a.missing=c.missing;a.valid=0===a.errors.length;return a},addSchema:function(){return d.addSchema.apply(d,arguments)},getSchema:function(){return d.getSchema.apply(d,
arguments)},getSchemaMap:function(){return d.getSchemaMap.apply(d,arguments)},getSchemaUris:function(){return d.getSchemaUris.apply(d,arguments)},getMissingUris:function(){return d.getMissingUris.apply(d,arguments)},dropSchemas:function(){d.dropSchemas.apply(d,arguments)},defineKeyword:function(){d.defineKeyword.apply(d,arguments)},defineError:function(a,d,m){if("string"!==typeof a||!/^[A-Z]+(_[A-Z]+)*$/.test(a))throw Error("Code name must be a string in UPPER_CASE_WITH_UNDERSCORES");if("number"!==
typeof d||0!==d%1||1E4>d)throw Error("Code number must be an integer > 10000");if("undefined"!==typeof k[a])throw Error("Error already defined: "+a+" as "+k[a]);if("undefined"!==typeof t[d])throw Error("Error code already used: "+t[d]+" as "+d);k[a]=d;t[d]=a;w[a]=w[d]=m;for(var b in z)m=z[b],m[a]&&(m[d]=m[d]||m[a])},reset:function(){d.reset();this.error=null;this.missing=[];this.valid=!0},missing:[],error:null,valid:!0,normSchema:l,resolveUrl:q,getDocumentUri:h,errorCodes:k}}var D={"+":!0,"#":!0,
".":!0,"/":!0,";":!0,"?":!0,"&":!0},v={"*":!0};c.prototype={toString:function(){return this.template},fillFromObject:function(a){return this.fill(function(d){return a[d]})}};var f=function(a,d,b,c,e){this.missing=[];this.missingMap={};this.formatValidators=a?Object.create(a.formatValidators):{};this.schemas=a?Object.create(a.schemas):{};this.collectMultiple=d;this.errors=[];this.handleError=d?this.collectError:this.returnError;c&&(this.checkRecursive=!0,this.scanned=[],this.scannedFrozen=[],this.scannedFrozenSchemas=
[],this.scannedFrozenValidationErrors=[],this.validatedSchemasKey="tv4_validation_id",this.validationErrorsKey="tv4_validation_errors_id");e&&(this.trackUnknownProperties=!0,this.knownPropertyPaths={},this.unknownPropertyPaths={});this.errorMessages=b;this.definedKeywords={};if(a)for(var h in a.definedKeywords)this.definedKeywords[h]=a.definedKeywords[h].slice(0)};f.prototype.defineKeyword=function(a,d){this.definedKeywords[a]=this.definedKeywords[a]||[];this.definedKeywords[a].push(d)};f.prototype.createError=
function(a,d,b,c,e){var h=this.errorMessages[a]||w[a];if("string"!==typeof h)return new g(a,"Unknown error code "+a+": "+JSON.stringify(d),d,b,c,e);h=h.replace(/\{([^{}]*)\}/g,function(a,m){var b=d[m];return"string"===typeof b||"number"===typeof b?b:a});return new g(a,h,d,b,c,e)};f.prototype.returnError=function(a){return a};f.prototype.collectError=function(a){a&&this.errors.push(a);return null};f.prototype.prefixErrors=function(a,d,b){for(var c=0,e=this.errors.length,c=a;c<e;c++)this.errors[c]=
this.errors[c].prefixWith(d,b);return this};f.prototype.banUnknownProperties=function(){for(var a in this.unknownPropertyPaths){var d=this.createError(k.UNKNOWN_PROPERTY,{path:a},a,"");if(d=this.handleError(d))return d}return null};f.prototype.addFormat=function(a,d){if("object"===typeof a){for(var b in a)this.addFormat(b,a[b]);return this}this.formatValidators[a]=d};f.prototype.resolveRefs=function(a,d){if(void 0!==a.$ref){d=d||{};if(d[a.$ref])return this.createError(k.CIRCULAR_REFERENCE,{urls:Object.keys(d).join(", ")},
"","");d[a.$ref]=!0;a=this.getSchema(a.$ref,d)}return a};f.prototype.getSchema=function(a,d){var b;if(void 0!==this.schemas[a])return b=this.schemas[a],this.resolveRefs(b,d);var c=a,e="";-1!==a.indexOf("#")&&(e=a.substring(a.indexOf("#")+1),c=a.substring(0,a.indexOf("#")));if("object"===typeof this.schemas[c]){b=this.schemas[c];e=decodeURIComponent(e);if(""===e)return this.resolveRefs(b,d);if("/"!==e.charAt(0))return;for(var e=e.split("/").slice(1),h=0,f=e.length,h=0;h<f;h++){var g=e[h].replace(/~1/g,
"/").replace(/~0/g,"~");if(void 0===b[g]){b=void 0;break}b=b[g]}if(void 0!==b)return this.resolveRefs(b,d)}void 0===this.missing[c]&&(this.missing.push(c),this.missing[c]=c,this.missingMap[c]=c)};f.prototype.searchSchemas=function(a,d){if(Array.isArray(a))for(var b=0,c=a.length,b=0;b<c;b++)this.searchSchemas(a[b],d);else if(a&&"object"===typeof a){if("string"===typeof a.id){a:{c=a.id;if(c.substring(0,d.length)===d){var e=c.substring(d.length);if(0<c.length&&"/"===c.charAt(d.length-1)||"#"===e.charAt(0)||
"?"===e.charAt(0)){c=!0;break a}}c=!1}c&&void 0===this.schemas[a.id]&&(this.schemas[a.id]=a)}for(b in a)"enum"!==b&&("object"===typeof a[b]?this.searchSchemas(a[b],d):"$ref"===b&&(c=h(a[b]))&&void 0===this.schemas[c]&&void 0===this.missingMap[c]&&(this.missingMap[c]=c))}};f.prototype.addSchema=function(a,d){if("string"!==typeof a||"undefined"===typeof d)if("object"===typeof a&&"string"===typeof a.id)d=a,a=d.id;else return;a===h(a)+"#"&&(a=h(a));this.schemas[a]=d;delete this.missingMap[a];l(d,a);this.searchSchemas(d,
a)};f.prototype.getSchemaMap=function(){var a={},d;for(d in this.schemas)a[d]=this.schemas[d];return a};f.prototype.getSchemaUris=function(a){var d=[],b;for(b in this.schemas)a&&!a.test(b)||d.push(b);return d};f.prototype.getMissingUris=function(a){var d=[],b;for(b in this.missingMap)a&&!a.test(b)||d.push(b);return d};f.prototype.dropSchemas=function(){this.schemas={};this.reset()};f.prototype.reset=function(){this.missing=[];this.missingMap={};this.errors=[]};f.prototype.validateAll=function(a,d,
b,c,e){var h;d=this.resolveRefs(d);if(!d)return null;if(d instanceof g)return this.errors.push(d),d;var f=this.errors.length,q,k=null,l=null;if(this.checkRecursive&&a&&"object"===typeof a){h=!this.scanned.length;if(a[this.validatedSchemasKey]){var n=a[this.validatedSchemasKey].indexOf(d);if(-1!==n)return this.errors=this.errors.concat(a[this.validationErrorsKey][n]),null}if(Object.isFrozen(a)&&(q=this.scannedFrozen.indexOf(a),-1!==q&&(n=this.scannedFrozenSchemas[q].indexOf(d),-1!==n)))return this.errors=
this.errors.concat(this.scannedFrozenValidationErrors[q][n]),null;this.scanned.push(a);if(Object.isFrozen(a))-1===q&&(q=this.scannedFrozen.length,this.scannedFrozen.push(a),this.scannedFrozenSchemas.push([])),k=this.scannedFrozenSchemas[q].length,this.scannedFrozenSchemas[q][k]=d,this.scannedFrozenValidationErrors[q][k]=[];else{if(!a[this.validatedSchemasKey])try{Object.defineProperty(a,this.validatedSchemasKey,{value:[],configurable:!0}),Object.defineProperty(a,this.validationErrorsKey,{value:[],
configurable:!0})}catch(r){a[this.validatedSchemasKey]=[],a[this.validationErrorsKey]=[]}l=a[this.validatedSchemasKey].length;a[this.validatedSchemasKey][l]=d;a[this.validationErrorsKey][l]=[]}}n=this.errors.length;d=this.validateBasic(a,d,e)||this.validateNumeric(a,d,e)||this.validateString(a,d,e)||this.validateArray(a,d,e)||this.validateObject(a,d,e)||this.validateCombinations(a,d,e)||this.validateHypermedia(a,d,e)||this.validateFormat(a,d,e)||this.validateDefinedKeywords(a,d,e)||null;if(h){for(;this.scanned.length;)delete this.scanned.pop()[this.validatedSchemasKey];
this.scannedFrozen=[];this.scannedFrozenSchemas=[]}if(d||n!==this.errors.length)for(;b&&b.length||c&&c.length;)h=b&&b.length?""+b.pop():null,e=c&&c.length?""+c.pop():null,d&&(d=d.prefixWith(h,e)),this.prefixErrors(n,h,e);null!==k?this.scannedFrozenValidationErrors[q][k]=this.errors.slice(f):null!==l&&(a[this.validationErrorsKey][l]=this.errors.slice(f));return this.handleError(d)};f.prototype.validateFormat=function(a,d){if("string"!==typeof d.format||!this.formatValidators[d.format])return null;
var b=this.formatValidators[d.format].call(null,a,d);return"string"===typeof b||"number"===typeof b?this.createError(k.FORMAT_CUSTOM,{message:b}).prefixWith(null,"format"):b&&"object"===typeof b?this.createError(k.FORMAT_CUSTOM,{message:b.message||"?"},b.dataPath||null,b.schemaPath||"/format"):null};f.prototype.validateDefinedKeywords=function(a,d,b){for(var c in this.definedKeywords)if("undefined"!==typeof d[c])for(var e=this.definedKeywords[c],h=0,f=e.length,h=0;h<f;h++){var g=(0,e[h])(a,d[c],d,
b);if("string"===typeof g||"number"===typeof g)return this.createError(k.KEYWORD_CUSTOM,{key:c,message:g}).prefixWith(null,"format");if(g&&"object"===typeof g){a=g.code;if("string"===typeof a){if(!k[a])throw Error("Undefined error code (use defineError): "+a);a=k[a]}else"number"!==typeof a&&(a=k.KEYWORD_CUSTOM);d="object"===typeof g.message?g.message:{key:c,message:g.message||"?"};c=g.schemaPath||"/"+c.replace(/~/g,"~0").replace(/\//g,"~1");return this.createError(a,d,g.dataPath||null,c)}}return null};
f.prototype.validateBasic=function(a,d,b){var c;return(c=this.validateType(a,d,b))||(c=this.validateEnum(a,d,b))?c.prefixWith(null,"type"):null};f.prototype.validateType=function(a,d){if(void 0===d.type)return null;var b=typeof a;null===a?b="null":Array.isArray(a)&&(b="array");var c=d.type;"object"!==typeof c&&(c=[c]);for(var e=0,h=c.length,e=0;e<h;e++){var g=c[e];if(g===b||"integer"===g&&"number"===b&&0===a%1)return null}return this.createError(k.INVALID_TYPE,{type:b,expected:c.join("/")})};f.prototype.validateEnum=
function(a,d){if(void 0===d["enum"])return null;for(var b=0,c=d["enum"].length,b=0;b<c;b++)if(n(a,d["enum"][b]))return null;return this.createError(k.ENUM_MISMATCH,{value:"undefined"!==typeof JSON?JSON.stringify(a):a})};f.prototype.validateNumeric=function(a,d,b){return this.validateMultipleOf(a,d,b)||this.validateMinMax(a,d,b)||this.validateNaN(a,d,b)||null};var u=Math.pow(2,-51),A=1-u;f.prototype.validateMultipleOf=function(a,d){var b=d.multipleOf||d.divisibleBy;if(void 0===b)return null;if("number"===
typeof a){var c=a/b%1;if(c>=u&&c<A)return this.createError(k.NUMBER_MULTIPLE_OF,{value:a,multipleOf:b})}return null};f.prototype.validateMinMax=function(a,d){if("number"!==typeof a)return null;if(void 0!==d.minimum){if(a<d.minimum)return this.createError(k.NUMBER_MINIMUM,{value:a,minimum:d.minimum}).prefixWith(null,"minimum");if(d.exclusiveMinimum&&a===d.minimum)return this.createError(k.NUMBER_MINIMUM_EXCLUSIVE,{value:a,minimum:d.minimum}).prefixWith(null,"exclusiveMinimum")}if(void 0!==d.maximum){if(a>
d.maximum)return this.createError(k.NUMBER_MAXIMUM,{value:a,maximum:d.maximum}).prefixWith(null,"maximum");if(d.exclusiveMaximum&&a===d.maximum)return this.createError(k.NUMBER_MAXIMUM_EXCLUSIVE,{value:a,maximum:d.maximum}).prefixWith(null,"exclusiveMaximum")}return null};f.prototype.validateNaN=function(a){return"number"!==typeof a?null:!0===isNaN(a)||Infinity===a||-Infinity===a?this.createError(k.NUMBER_NOT_A_NUMBER,{value:a}).prefixWith(null,"type"):null};f.prototype.validateString=function(a,
d,b){return this.validateStringLength(a,d,b)||this.validateStringPattern(a,d,b)||null};f.prototype.validateStringLength=function(a,d){return"string"!==typeof a?null:void 0!==d.minLength&&a.length<d.minLength?this.createError(k.STRING_LENGTH_SHORT,{length:a.length,minimum:d.minLength}).prefixWith(null,"minLength"):void 0!==d.maxLength&&a.length>d.maxLength?this.createError(k.STRING_LENGTH_LONG,{length:a.length,maximum:d.maxLength}).prefixWith(null,"maxLength"):null};f.prototype.validateStringPattern=
function(a,d){return"string"!==typeof a||void 0===d.pattern?null:(new RegExp(d.pattern)).test(a)?null:this.createError(k.STRING_PATTERN,{pattern:d.pattern}).prefixWith(null,"pattern")};f.prototype.validateArray=function(a,d,b){return Array.isArray(a)?this.validateArrayLength(a,d,b)||this.validateArrayUniqueItems(a,d,b)||this.validateArrayItems(a,d,b)||null:null};f.prototype.validateArrayLength=function(a,d){var b;return void 0!==d.minItems&&a.length<d.minItems&&(b=this.createError(k.ARRAY_LENGTH_SHORT,
{length:a.length,minimum:d.minItems}).prefixWith(null,"minItems"),this.handleError(b))||void 0!==d.maxItems&&a.length>d.maxItems&&(b=this.createError(k.ARRAY_LENGTH_LONG,{length:a.length,maximum:d.maxItems}).prefixWith(null,"maxItems"),this.handleError(b))?b:null};f.prototype.validateArrayUniqueItems=function(a,d){if(d.uniqueItems)for(var b=0,c=a.length,b=0;b<c;b++)for(var e=0,e=b+1;e<c;e++)if(n(a[b],a[e])){var h=this.createError(k.ARRAY_UNIQUE,{match1:b,match2:e}).prefixWith(null,"uniqueItems");
if(this.handleError(h))return h}return null};f.prototype.validateArrayItems=function(a,d,b){if(void 0===d.items)return null;var c,e;if(Array.isArray(d.items)){var h=a.length;for(e=0;e<h;e++)if(e<d.items.length){if(c=this.validateAll(a[e],d.items[e],[e],["items",e],b+"/"+e))return c}else if(void 0!==d.additionalItems)if("boolean"===typeof d.additionalItems){if(!d.additionalItems&&(c=this.createError(k.ARRAY_ADDITIONAL_ITEMS,{}).prefixWith(""+e,"additionalItems"),this.handleError(c)))return c}else if(c=
this.validateAll(a[e],d.additionalItems,[e],["additionalItems"],b+"/"+e))return c}else for(h=a.length,e=0;e<h;e++)if(c=this.validateAll(a[e],d.items,[e],["items"],b+"/"+e))return c;return null};f.prototype.validateObject=function(a,d,b){return"object"!==typeof a||null===a||Array.isArray(a)?null:this.validateObjectMinMaxProperties(a,d,b)||this.validateObjectRequiredProperties(a,d,b)||this.validateObjectProperties(a,d,b)||this.validateObjectDependencies(a,d,b)||null};f.prototype.validateObjectMinMaxProperties=
function(a,d){var b=Object.keys(a),c;return void 0!==d.minProperties&&b.length<d.minProperties&&(c=this.createError(k.OBJECT_PROPERTIES_MINIMUM,{propertyCount:b.length,minimum:d.minProperties}).prefixWith(null,"minProperties"),this.handleError(c))||void 0!==d.maxProperties&&b.length>d.maxProperties&&(c=this.createError(k.OBJECT_PROPERTIES_MAXIMUM,{propertyCount:b.length,maximum:d.maxProperties}).prefixWith(null,"maxProperties"),this.handleError(c))?c:null};f.prototype.validateObjectRequiredProperties=
function(a,d){if(void 0!==d.required)for(var b=0,c=d.required.length,b=0;b<c;b++){var e=d.required[b];if(void 0===a[e]&&(e=this.createError(k.OBJECT_REQUIRED,{key:e}).prefixWith(null,""+b).prefixWith(null,"required"),this.handleError(e)))return e}return null};f.prototype.validateObjectProperties=function(a,d,b){var c,e;for(e in a){var h=b+"/"+e.replace(/~/g,"~0").replace(/\//g,"~1"),g=!1;if(void 0!==d.properties&&void 0!==d.properties[e]&&(g=!0,c=this.validateAll(a[e],d.properties[e],[e],["properties",
e],h)))return c;if(void 0!==d.patternProperties)for(var f in d.patternProperties)if((new RegExp(f)).test(e)&&(g=!0,c=this.validateAll(a[e],d.patternProperties[f],[e],["patternProperties",f],h)))return c;if(g)this.trackUnknownProperties&&(this.knownPropertyPaths[h]=!0,delete this.unknownPropertyPaths[h]);else if(void 0!==d.additionalProperties)if(this.trackUnknownProperties&&(this.knownPropertyPaths[h]=!0,delete this.unknownPropertyPaths[h]),"boolean"===typeof d.additionalProperties){if(!d.additionalProperties&&
(c=this.createError(k.OBJECT_ADDITIONAL_PROPERTIES,{}).prefixWith(e,"additionalProperties"),this.handleError(c)))return c}else{if(c=this.validateAll(a[e],d.additionalProperties,[e],["additionalProperties"],h))return c}else this.trackUnknownProperties&&!this.knownPropertyPaths[h]&&(this.unknownPropertyPaths[h]=!0)}return null};f.prototype.validateObjectDependencies=function(a,d,b){var c;if(void 0!==d.dependencies)for(var e in d.dependencies)if(void 0!==a[e]){var h=d.dependencies[e];if("string"===typeof h){if(void 0===
a[h]&&(c=this.createError(k.OBJECT_DEPENDENCY_KEY,{key:e,missing:h}).prefixWith(null,e).prefixWith(null,"dependencies"),this.handleError(c)))return c}else if(Array.isArray(h))for(var g=0,f=h.lenth,g=0;g<f;g++){if(c=h[g],void 0===a[c]&&(c=this.createError(k.OBJECT_DEPENDENCY_KEY,{key:e,missing:c}).prefixWith(null,""+g).prefixWith(null,e).prefixWith(null,"dependencies"),this.handleError(c)))return c}else if(c=this.validateAll(a,h,[],["dependencies",e],b))return c}return null};f.prototype.validateCombinations=
function(a,d,b){return this.validateAllOf(a,d,b)||this.validateAnyOf(a,d,b)||this.validateOneOf(a,d,b)||this.validateNot(a,d,b)||null};f.prototype.validateAllOf=function(a,b,c){if(void 0===b.allOf)return null;for(var e,h=0,g=b.allOf.length,h=0;h<g;h++)if(e=this.validateAll(a,b.allOf[h],[],["allOf",h],c))return e;return null};f.prototype.validateAnyOf=function(a,b,c){if(void 0===b.anyOf)return null;var e=[],h=this.errors.length,g,f;this.trackUnknownProperties&&(g=this.unknownPropertyPaths,f=this.knownPropertyPaths);
for(var q=!0,l=0,n=b.anyOf.length,l=0;l<n;l++){this.trackUnknownProperties&&(this.unknownPropertyPaths={},this.knownPropertyPaths={});var r=this.errors.length,t=this.validateAll(a,b.anyOf[l],[],["anyOf",l],c);if(null===t&&r===this.errors.length){this.errors=this.errors.slice(0,h);if(this.trackUnknownProperties){for(var p in this.knownPropertyPaths)f[p]=!0,delete g[p];for(var D in this.unknownPropertyPaths)f[D]||(g[D]=!0);q=!1;continue}return null}t&&e.push(t.prefixWith(null,""+l).prefixWith(null,
"anyOf"))}this.trackUnknownProperties&&(this.unknownPropertyPaths=g,this.knownPropertyPaths=f);if(q)return e=e.concat(this.errors.slice(h)),this.errors=this.errors.slice(0,h),this.createError(k.ANY_OF_MISSING,{},"","/anyOf",e)};f.prototype.validateOneOf=function(a,b,c){if(void 0===b.oneOf)return null;var e=null,h=[],g=this.errors.length,f,q;this.trackUnknownProperties&&(f=this.unknownPropertyPaths,q=this.knownPropertyPaths);for(var l=0,n=b.oneOf.length,l=0;l<n;l++){this.trackUnknownProperties&&(this.unknownPropertyPaths=
{},this.knownPropertyPaths={});var r=this.errors.length,t=this.validateAll(a,b.oneOf[l],[],["oneOf",l],c);if(null===t&&r===this.errors.length){if(null===e)e=l;else return this.errors=this.errors.slice(0,g),this.createError(k.ONE_OF_MULTIPLE,{index1:e,index2:l},"","/oneOf");if(this.trackUnknownProperties){for(var p in this.knownPropertyPaths)q[p]=!0,delete f[p];for(var D in this.unknownPropertyPaths)q[D]||(f[D]=!0)}}else t&&h.push(t)}this.trackUnknownProperties&&(this.unknownPropertyPaths=f,this.knownPropertyPaths=
q);if(null===e)return h=h.concat(this.errors.slice(g)),this.errors=this.errors.slice(0,g),this.createError(k.ONE_OF_MISSING,{},"","/oneOf",h);this.errors=this.errors.slice(0,g);return null};f.prototype.validateNot=function(a,b,c){if(void 0===b.not)return null;var e=this.errors.length,h,g;this.trackUnknownProperties&&(h=this.unknownPropertyPaths,g=this.knownPropertyPaths,this.unknownPropertyPaths={},this.knownPropertyPaths={});a=this.validateAll(a,b.not,null,null,c);b=this.errors.slice(e);this.errors=
this.errors.slice(0,e);this.trackUnknownProperties&&(this.unknownPropertyPaths=h,this.knownPropertyPaths=g);return null===a&&0===b.length?this.createError(k.NOT_PASSED,{},"","/not"):null};f.prototype.validateHypermedia=function(a,b,h){if(!b.links)return null;for(var g,f=0,q=b.links.length,f=0;f<q;f++)if(g=b.links[f],"describedby"===g.rel){g=new c(g.href);for(var l=!0,k=0,n=g.varNames.length,k=0;k<n;k++)if(!(g.varNames[k]in a)){l=!1;break}if(l&&(g={$ref:g.fillFromObject(a)},g=this.validateAll(a,g,
[],["links",f],h)))return g}};var k={INVALID_TYPE:0,ENUM_MISMATCH:1,ANY_OF_MISSING:10,ONE_OF_MISSING:11,ONE_OF_MULTIPLE:12,NOT_PASSED:13,NUMBER_MULTIPLE_OF:100,NUMBER_MINIMUM:101,NUMBER_MINIMUM_EXCLUSIVE:102,NUMBER_MAXIMUM:103,NUMBER_MAXIMUM_EXCLUSIVE:104,NUMBER_NOT_A_NUMBER:105,STRING_LENGTH_SHORT:200,STRING_LENGTH_LONG:201,STRING_PATTERN:202,OBJECT_PROPERTIES_MINIMUM:300,OBJECT_PROPERTIES_MAXIMUM:301,OBJECT_REQUIRED:302,OBJECT_ADDITIONAL_PROPERTIES:303,OBJECT_DEPENDENCY_KEY:304,ARRAY_LENGTH_SHORT:400,
ARRAY_LENGTH_LONG:401,ARRAY_UNIQUE:402,ARRAY_ADDITIONAL_ITEMS:403,FORMAT_CUSTOM:500,KEYWORD_CUSTOM:501,CIRCULAR_REFERENCE:600,UNKNOWN_PROPERTY:1E3},t={},x;for(x in k)t[k[x]]=x;var w={INVALID_TYPE:"Invalid type: {type} (expected {expected})",ENUM_MISMATCH:"No enum match for: {value}",ANY_OF_MISSING:'Data does not match any schemas from "anyOf"',ONE_OF_MISSING:'Data does not match any schemas from "oneOf"',ONE_OF_MULTIPLE:'Data is valid against more than one schema from "oneOf": indices {index1} and {index2}',
NOT_PASSED:'Data matches schema from "not"',NUMBER_MULTIPLE_OF:"Value {value} is not a multiple of {multipleOf}",NUMBER_MINIMUM:"Value {value} is less than minimum {minimum}",NUMBER_MINIMUM_EXCLUSIVE:"Value {value} is equal to exclusive minimum {minimum}",NUMBER_MAXIMUM:"Value {value} is greater than maximum {maximum}",NUMBER_MAXIMUM_EXCLUSIVE:"Value {value} is equal to exclusive maximum {maximum}",NUMBER_NOT_A_NUMBER:"Value {value} is not a valid number",STRING_LENGTH_SHORT:"String is too short ({length} chars), minimum {minimum}",
STRING_LENGTH_LONG:"String is too long ({length} chars), maximum {maximum}",STRING_PATTERN:"String does not match pattern: {pattern}",OBJECT_PROPERTIES_MINIMUM:"Too few properties defined ({propertyCount}), minimum {minimum}",OBJECT_PROPERTIES_MAXIMUM:"Too many properties defined ({propertyCount}), maximum {maximum}",OBJECT_REQUIRED:"Missing required property: {key}",OBJECT_ADDITIONAL_PROPERTIES:"Additional properties not allowed",OBJECT_DEPENDENCY_KEY:"Dependency failed - key must exist: {missing} (due to key: {key})",
ARRAY_LENGTH_SHORT:"Array is too short ({length}), minimum {minimum}",ARRAY_LENGTH_LONG:"Array is too long ({length}), maximum {maximum}",ARRAY_UNIQUE:"Array items are not unique (indices {match1} and {match2})",ARRAY_ADDITIONAL_ITEMS:"Additional items not allowed",FORMAT_CUSTOM:"Format validation failed ({message})",KEYWORD_CUSTOM:"Keyword failed: {key} ({message})",CIRCULAR_REFERENCE:"Circular $refs: {urls}",UNKNOWN_PROPERTY:"Unknown property (not in schema)"};g.prototype=Object.create(Error.prototype);
g.prototype.constructor=g;g.prototype.name="ValidationError";g.prototype.prefixWith=function(a,b){null!==a&&(a=a.replace(/~/g,"~0").replace(/\//g,"~1"),this.dataPath="/"+a+this.dataPath);null!==b&&(b=b.replace(/~/g,"~0").replace(/\//g,"~1"),this.schemaPath="/"+b+this.schemaPath);if(null!==this.subErrors)for(var c=0,e=this.subErrors.length,c=0;c<e;c++)this.subErrors[c].prefixWith(a,b);return this};var z={};x=p();x.addLanguage("en-us",w);return x.tv4=x},K=K?K:new function(){function a(a,c){I({url:a,
async:!1,cache:c.cache,contentType:"text/plain;charset="+c.encoding,dataType:"text",success:function(a,e){b(a,c.mode)}})}function b(a,b){for(var c="",g=a.split(/\n/),p=/(\{\d+\})/g,D=/\{(\d+)\}/g,v=/(\\u.{4})/ig,f=0,w=g.length,f=0;f<w;f++)if(g[f]=g[f].replace(/^\s\s*/,"").replace(/\s\s*$/,""),0<g[f].length&&"#"!=g[f].match("^#")){var A=g[f].split("=");if(0<A.length){for(var k=unescape(A[0]).replace(/^\s\s*/,"").replace(/\s\s*$/,""),t=1==A.length?"":A[1];"\\"==t.match(/\\$/);)t=t.substring(0,t.length-
1),t+=g[++f].replace(/\s\s*$/,"");for(var x=2;x<A.length;x++)t+="="+A[x];t=t.replace(/^\s\s*/,"").replace(/\s\s*$/,"");if("map"==b||"both"==b){if(A=t.match(v))for(x=0;x<A.length;x++)t=t.replace(A[x],n(A[x]));r.map[k]=t}if("vars"==b||"both"==b)if(t=t.replace(/"/g,'\\"'),e(k),p.test(t)){for(var A=t.split(p),x=!0,u="",z=[],m=0;m<A.length;m++)!p.test(A[m])||0!==z.length&&-1!==z.indexOf(A[m])||(x||(u+=","),u+=A[m].replace(D,"v$1"),z.push(A[m]),x=!1);c+=k+"=function("+u+"){";k='"'+t.replace(D,'"+v$1+"')+
'"';c+="return "+k+";};"}else c+=k+'="'+t+'";'}}eval(c)}function e(a){if(/\./.test(a)){var b="";a=a.split(/\./);for(var c=0;c<a.length;c++)0<c&&(b+="."),b+=a[c],eval("typeof "+b+' == "undefined"')&&eval(b+"={};")}}function n(a){var b=[];a=parseInt(a.substr(2),16);0<=a&&a<Math.pow(2,16)&&b.push(a);a="";for(var c=0;c<b.length;++c)a+=String.fromCharCode(b[c]);return a}var r={map:{}};this.properties=function(b){b=c.Utility.extend({name:c.Configuration.MessageBundle,language:"",path:"",mode:"vars",cache:!1,
encoding:"UTF-8",callback:null},b);if(null===b.language||""===b.language){var e=b,l=navigator.language||navigator.userLanguage,l=l.toLowerCase();3<l.length&&(l=l.substring(0,3)+l.substring(3).toUpperCase());e.language=l}null===b.language&&(b.language="");for(var e=(e=b.name)&&e.constructor==Array?e:[e],l=0,g=e.length,l=0;l<g;l++)a(b.path+e[l]+".properties",b),2<=b.language.length&&a(b.path+e[l]+"_"+b.language.substring(0,2)+".properties",b),5<=b.language.length&&a(b.path+e[l]+"_"+b.language.substring(0,
5)+".properties",b);b.callback&&b.callback()};this.prop=function(a){var b=r.map[a];if(!b)return"["+a+"]";var c;2==arguments.length&&Array.isArray(arguments[1])&&(c=arguments[1]);var e;if("string"==typeof b){for(e=0;-1!=(e=b.indexOf("\\",e));)b="t"==b.charAt(e+1)?b.substring(0,e)+"\t"+b.substring(e++ +2):"r"==b.charAt(e+1)?b.substring(0,e)+"\r"+b.substring(e++ +2):"n"==b.charAt(e+1)?b.substring(0,e)+"\n"+b.substring(e++ +2):"f"==b.charAt(e+1)?b.substring(0,e)+"\f"+b.substring(e++ +2):"\\"==b.charAt(e+
1)?b.substring(0,e)+"\\"+b.substring(e++ +2):b.substring(0,e)+b.substring(e+1);var n=[],p,u;for(e=0;e<b.length;)if("'"==b.charAt(e))if(e==b.length-1)b=b.substring(0,e);else if("'"==b.charAt(e+1))b=b.substring(0,e)+b.substring(++e);else{for(p=e+2;-1!=(p=b.indexOf("'",p));)if(p==b.length-1||"'"!=b.charAt(p+1)){b=b.substring(0,e)+b.substring(e+1,p)+b.substring(p+1);e=p-1;break}else b=b.substring(0,p)+b.substring(++p);-1==p&&(b=b.substring(0,e)+b.substring(e+1))}else if("{"==b.charAt(e))if(p=b.indexOf("}",
e+1),-1==p)e++;else if(u=parseInt(b.substring(e+1,p)),!isNaN(u)&&0<=u){var f=b.substring(0,e);""!==f&&n.push(f);n.push(u);e=0;b=b.substring(p+1)}else e=p+1;else e++;""!==b&&n.push(b);b=n;r.map[a]=n}if(0===b.length)return"";if(1==b.lengh&&"string"==typeof b[0])return b[0];f="";n=b.length;for(e=0;e<n;e++)f="string"==typeof b[e]?f+b[e]:c&&b[e]<c.length?f+c[b[e]]:!c&&b[e]+1<arguments.length?f+arguments[b[e]+1]:f+("{"+b[e]+"}");return f}};c.Utility.BundleObject={name:"",mode:"both",cache:!0};c.Utility.ResourceBundle=
{getBundle:function(){return K.properties.apply(this,arguments)},getString:function(){return K.prop.apply(this,arguments)}};c.Utility.MessageReader={getMessage:function(a){for(var b=c.Utility.ResourceBundle.getString.apply(this,arguments),e=a.length,n=a;0<e&&b=="["+a+"]";)e=a.lastIndexOf("."),a=a.substring(0,e),b=c.Utility.ResourceBundle.getString.apply(this,arguments);return a?b:"["+n+"]"}};c.Utility.MessageKeyFormatter={delimiter:".",format:function(a){var b="";a&&a.level&&(b+=a.level,a.kind&&(b+=
this.delimiter+a.kind,a.rule&&(b+=this.delimiter+a.rule,a.values.title&&(b+=this.delimiter+a.values.title))));return b?b:""}};c.ValidationFramework=c.ValidationFramework?c.ValidationFramework:new function(){var a;void 0===a&&(a=new U);this.supportsValidation=function(){return null!==a};this.registerSchema=function(b,c){a.addSchema(b,c)};this.getSchema=function(b){return a.getSchema(b)};this.getSchemas=function(){return a.getSchemaMap()};this.clearSchemas=function(){a.dropSchemas()};this.validate=
function(b,c){return a.validateMultiple(b,c)};this.getValidationMessages=function(){return a.error}};w=v.Model.extend({schema:null,mock:!1,validationMessages:{valid:!0},supportsValidation:function(){return null!==this.schema?!0:!1},isValid:function(){this.validate();return this.validationMessages.valid},validate:function(){this.supportsValidation()&&c.ValidationFramework.supportsValidation()?this.validationMessages=c.ValidationFramework.validate(this.toJSON(),this.schema):this.validationMessages.valid=
!0;return this.validationMessages},crossOrigin:!1,sync:function(a,b,e){e||(e={});!0===this.crossOrigin&&(e.crossDomain=!0);e.xhrFields||(e.xhrFields={withCredentials:!0});this.mock&&(e.mock=this.mock);return c.sync(a,b,e)}});c.Utility.extend(w,c.Object);var N=v.Collection.extend({schema:null,mock:!1,validationMessages:{valid:!0},supportsValidation:function(){return this.schema&&this.schema!=={}},isValid:function(){return this.validationMessages?this.validationMessages.valid:!0},getValidationMessages:function(){return this.validationMessages&&
this.validationMessages.messages?this.validationMessages.messages:[]},validate:function(){if(this.supportsValidation()&&c.ValidationFramework.supportsValidation()){var a=[];this.validationMessages.messages=a;this.validationMessages.valid=!0;var b=this.toJSON(),e=0,n=b.length;C.debug("AUGMENTED: Collection Validate: Beginning with "+n+" models.");for(e=0;e<n;e++)a[e]=c.ValidationFramework.validate(b[e],this.schema),a[e].valid||(this.validationMessages.valid=!1);C.debug("AUGMENTED: Collection Validate: Completed isValid "+
this.validationMessages.valid)}else this.validationMessages.valid=!0;return this.validationMessages},crossOrigin:!1,sync:function(a,b,e){e||(e={});!0===this.crossOrigin&&(e.crossDomain=!0);e.xhrFields||(e.xhrFields={withCredentials:!0});this.mock&&(e.mock=this.mock);return c.sync(a,b,e)},save:function(a){c.sync("create",this,a)},update:function(a){c.sync("update",this,a)},sortByKey:function(a){if(a){var b=this.toJSON();b&&(a=c.Utility.Sort(b,a),this.reset(a))}}});c.Utility.extend(N,c.Object);var O=
c.PaginatedCollection=N.extend({paginationConfiguration:{currentPageParam:"page",pageSizeParam:"per_page"},pageSize:20,currentPage:1,totalPages:1,setPageSize:function(a){a&&(this.pageSize=a);this.refresh()},setCurrentPage:function(a){a||(a=1);this.currentPage=a;this.refresh()},setPaginationConfiguration:function(a){this.paginationConfiguration=a},fetch:function(a){a=a?a:{};var b=this.paginationConfiguration,e={};e[b.currentPageParam]=this.currentPage;e[b.pageSizeParam]=this.pageSize;a.data=e;return c.Collection.prototype.fetch.call(this,
a)},nextPage:function(){this.currentPage<this.totalPages&&(this.currentPage+=1,this.refresh())},previousPage:function(){0<this.currentPage&&(--this.currentPage,this.refresh())},goToPage:function(a){a&&a<this.totalPages&&0<a&&(this.currentPage=a,this.refresh())},firstPage:function(){this.currentPage=1;this.refresh()},lastPage:function(){this.currentPage=this.totalPages;this.refresh()},refresh:function(){this.fetch()}}),H={github:"github",solr:"solr",database:"database"};c.PaginationFactory={type:H,
getPaginatedCollection:function(a,b){var c=b?b:{},n=null;a||(a=H.github);a===H.github?(n=new O(c),n.setPaginationConfiguration({currentPageParam:"page",pageSizeParam:"per_page"})):a===H.solr?(n=new O(c),n.setPaginationConfiguration({currentPageParam:"start",pageSizeParam:"rows"})):a===H.database&&(n=new O(c),n.setPaginationConfiguration({currentPageParam:"offset",pageSizeParam:"limit"}));return n}};var V=v.View.extend({init:function(a){},initialize:function(a){this.init(a);this.render=c.Utility.wrap(this.render,
function(a){this.beforeRender();a.apply(this);a();this.afterRender();return this})},beforeRender:function(){return this},render:function(){return this},afterRender:function(){return this},name:"",setName:function(a){this.name=a},getName:function(){return this.name},permissions:{include:[],exclude:[]},addPermission:function(a,b){b||(b=!1);null===a||Array.isArray(a)||(b?this.permissions.exclude:this.permissions.include).push(a)},removePermission:function(a,b){b||(b=!1);if(null!==a&&!Array.isArray(a)){var c=
b?this.permissions.exclude:this.permissions.include;c.splice(c.indexOf(a),1)}},setPermissions:function(a,b){b||(b=!1);null!==a&&Array.isArray(a)&&(b?this.permissions.exclude=a:this.permissions.include=a)},getPermissions:function(){return this.permissions},clearPermissions:function(){this.permissions={include:[],exclude:[]}},matchesPermission:function(a,b){b||(b=!1);return-1!==(b?this.permissions.exclude:this.permissions.include).indexOf(a)},canDisplay:function(){return!0}});c.Model=w;c.Collection=
N;c.View=V;c.history=v.history;c.History=v.History;c.Router=v.Router;c.Model.extend=c.Collection.extend=c.Router.extend=c.View.extend=c.History.extend=c.extend;var W=function(a){this.isPersisted=a;this.myStore=null;this.isSupported=function(){return"undefined"!==typeof Storage};this.isSupported()?(C.debug("AUGMENTED: localStorage exists"),this.myStore=this.isPersisted?localStorage:sessionStorage):C.warn("AUGMENTED: No localStorage.");this.getItem=function(a){return(a=this.myStore.getItem(a))?JSON.parse(a):
null};this.setItem=function(a,c){this.myStore.setItem(a,JSON.stringify(c))};this.removeItem=function(a){this.myStore.removeItem(a)};this.clear=function(){this.myStore.clear()};this.key=function(a){return this.myStore.key(a)};this.length=function(){return this.myStore.length}},Y=function(a,b){var e=X.getStorage(a);this.myNameSpacedStore=new c.Utility.AugmentedMap;this.namespace=b;this.isSupported=function(){return e&&e.isSupported()};this.isSupported()&&this.namespace&&e.setItem(this.namespace,JSON.stringify(this.myNameSpacedStore.toJSON()));
this.getItem=function(a){var b={};try{b=JSON.parse(e.getItem(this.namespace))}catch(c){return C.error("AUGMENTED: Augmented Local Strorage could not parse item map from storage!"),null}this.myNameSpacedStore.clear();this.myNameSpacedStore.marshall(b);if(a=this.myNameSpacedStore.get(a)){var p;try{p=JSON.parse(a)}catch(c){p=a}return p}return null};this.setItem=function(a,p){this.myNameSpacedStore||(this.myNameSpacedStore=new c.Utility.AugmentedMap);this.myNameSpacedStore.set(a,p);e.setItem(b,JSON.stringify(this.myNameSpacedStore.toJSON()))};
this.removeItem=function(a){this.getItem(a);this.myNameSpacedStore.remove(a);e.setItem(b,JSON.stringify(this.myNameSpacedStore.toJSON()))};this.clear=function(){this.myNameSpacedStore.clear();e.setItem(b,JSON.stringify(this.myNameSpacedStore.toJSON()))};this.key=function(a){return this.myNameSpacedStore.key(a)};this.length=function(){return this.myNameSpacedStore.size()}},X=c.LocalStorageFactory={getStorage:function(a,b){var c=null;return(c=b?new Y(a,b):new W(a))&&c.isSupported()?c:null}};c.LocalStorageCollection=
c.Collection.extend({key:"augmented.localstorage.collection.key",persist:!1,storage:null,url:null,initialize:function(a,b){b&&b.persist&&(this.persist=b.persist);b&&b.key&&(this.key=b.key);this.storage=c.LocalStorageFactory.getStorage(this.persist,"augmented.localstorage.collection")},fetch:function(a){this.sync("read",this,a)},save:function(a){this.sync("create",this,a)},update:function(a){this.sync("update",this,a)},destroy:function(a){this.sync("delete",this,a)},sync:function(a,b,c){b={};"create"===
a||"update"===a?(b=this.toJSON(),this.storage.setItem(this.key,b)):"delete"===a?this.storage.removeItem(this.key):(b=this.storage.getItem(this.key),this.reset(b));return{}}});c.Utility.Stack=function(){this.stack=[];this.empty=function(){return 0===this.stack.length};this.peek=function(){return this.stack[0]};this.pop=function(){return this.stack.pop()};this.push=function(a){this.stack.push(a)};this.search=function(a){return this.stack.indexOf(a)};this.size=function(){return this.stack.length};this.clear=
function(){this.stack.splice(0,this.stack.length)};this.toArray=function(){return this.stack}};c.Utility.AsynchronousQueue=function(a){var b=a?a:c.Configuration.AsynchronousQueueTimeout;this.queue={};this.add=function(){var a=arguments;if(0>=a.length)return!1;c.Utility.extend(this.queue,a)};this.clear=function(){0<this.queue.length&&this.queue.splice(0,this.queue.length)};this.process=function(){arguments&&c.Utility.extend(this.queue,arguments);var a=this.queue,n=a.length;if(0>=n)return!1;(function q(c){if(c>=
n||"function"!==typeof a[c])return!1;window.setTimeout(function(){a[c]();q(c+1)},b)})(0);return!0};this.getTimeout=function(){return b};this.getQueue=function(){return this.queue}};w=c.Application=function(a){var b;this.started=!1;b?b.clear():b=new c.Utility.AugmentedMap;a?b.set("name",a):b.set("name","untitled");this.initialize=function(){};this.beforeInitialize=function(){};this.afterInitialize=function(){};this.getName=function(){return this.getMetadataItem("name")};this.setName=function(a){return this.setMetadataItem("name",
a)};this.getMetadata=function(){return b};this.setMetadataItem=function(a,c){b.set(a,c)};this.getMetadataItem=function(a){return b.get(a)};this.start=function(){(this.started=(new c.Utility.AsynchronousQueue(c.Configuration.ApplicationInitProcessTimeout)).process(this.beforeInitialize(),this.initialize(),this.afterInitialize(),function(){c.History.started||c.history.start()}()))||this.stop()};this.stop=function(){c.History.started&&c.history.stop();this.started=!1}};c.Application.prototype.constructor=
w;return c});
