/*
 Apache-2.0
*/
(function(f){"object"===typeof exports?module.exports=f(require("underscore","augmented")):"function"===typeof define&&define.amd?define(["underscore","augmented"],f):window.Augmented.Presentation=f(window._,window.Augmented)})(function(f,c){c.Presentation={};c.Presentation.VERSION=c.VERSION;c.Utility.extend(c.View,{getFormData:function(a){a=function(a){for(var b=[],d=0,d=0;d<a.length;d++){var c=a[d],g={};g.name=c.name;g.value=c.value;g.type=c.type;"checkbox"===c.type&&(g.value=c.checked?"on":"off");
b.push(g)}return b}(document.querySelectorAll(a+" > input"));return f(a).reduce(function(a,b){switch(b.type){case "number":""!==b.value&&(a[b.name]=parseFloat(b.value));break;case "checkbox":a[b.name]="on"===b.value?!0:!1;break;default:a[b.name]=b.value}return a},{})}});var k=c.View.prototype.delegateEvents,l=c.View.prototype.undelegateEvents;c.Presentation.Mediator=c.View.extend({defaultChannel:"augmentedChannel",channels:{},observeColleague:function(a,e,b){a instanceof c.Presentation.Colleague&&
(b||(b=this.defaultChannel),this.subscribe(b,e,a,!1))},dismissColleague:function(a,e){a instanceof c.Presentation.Colleague&&(e||(e=this.defaultChannel),this.unsubscribe(e,callback,a))},subscribe:function(a,e,b,c){this.channels[a]||(this.channels[a]=[]);this.channels[a].push({fn:e,context:b||this,once:c})},publish:function(a){if(this.channels[a])for(var e=[].slice.call(arguments,1),b,c=0;c<this.channels[a].length;c++)b=this.channels[a][c],b.fn.apply(b.context,e),b.once&&(this.unsubscribe(a,b.fn,b.context),
c--)},unsubscribe:function(a,c,b){if(this.channels[a])for(var d=0;d<this.channels[a].length;d++)c=this.channels[a][d],c.fn===fn&&c.context===b&&(this.channels[a].splice(d,1),d--)},subscribeOnce:function(a,c,b){this.subscribe(a,c,b,!0)},getColleagues:function(a){return this.getChannel(a).context},getChannels:function(){return this.channels},getChannel:function(a){a||(a=this.defaultChannel);return this.channels[a]},getDefaultChannel:function(){return this.channels[this.defaultChannel]}});var m=c.Presentation.Colleague=
c.View.extend({delegateEvents:function(){k.apply(this,arguments);this.setSubscriptions()},undelegateEvents:function(){l.apply(this,arguments);this.unsetSubscriptions()},subscriptions:{},getSubscriptions:function(){return this.subscriptions},setSubscriptions:function(a){a&&c.Utility.extend(this.subscriptions||{},a);if((a=a||this.subscriptions)&&0!==a.length){this.unsetSubscriptions(a);var e=0;for(e;e<a.length;e++){var b=a[e],d=!1;b.$once&&(b=b.$once,d=!0);"string"===typeof b&&(b=this[b]);this.subscribe(b.channel,
b,this,d)}}},unsetSubscriptions:function(a){if((a=a||this.subscriptions)&&0!==a.length){var c=0;for(c;c<a.length;c++){var b=a[c];b.$once&&(b=b.$once);"string"==typeof b&&(b=this[b]);this.unsubscribe(b.channel,b.$once||b,this)}}}}),h=c.Presentation.Application=function(){c.Application.apply(this,arguments);this.Mediators=[];this.Stylesheets=[];this.breadcrumb=new c.Utility.Stack;this.initialize=function(){this.Stylesheets&&0<this.Stylesheets.length&&this.attachStylesheets()};this.registerMediator=
function(a){a&&this.Mediators.push(a)};this.deregisterMediator=function(a){a&&(a=this.Mediators.indexOf(a),-1!=a&&this.Mediators.splice(a,1))};this.getMediators=function(){return this.Mediators};this.registerStylesheet=function(a){a&&this.Stylesheets.push(a)};this.deregisterStylesheet=function(a){a&&this.Stylesheets.splice(this.Stylesheets.indexOf(a),1)};this.attachStylesheets=function(){var a=document.getElementsByTagName("head")[0],c=0;for(c;c<this.Stylesheets.length;c++){var b=document.createElement("link");
b.type="text/css";b.rel="stylesheet";b.href=this.Stylesheets[c];a.appendChild(b)}};this.setCurrentBreadcrumb=function(a,c){1<this.breadcrumb.size()&&this.breadcrumb.pop();this.breadcrumb.push({uri:a,name:c})};this.getCurrentBreadcrumb=function(){return this.breadcrumb.peek()};this.getBreadcrumbs=function(){return this.breadcrumb.toArray()}};h.prototype.constructor=h;var n=c.PaginatedCollection.extend({});c.Presentation.AutomaticTable=m.extend({columns:{},uri:null,data:[],collection:null,isInitalized:!1,
initialize:function(a){this.collection?this.collection.reset():this.collection=new n;a&&(a.schema&&(this.schema=a.schema),a.el&&(this.el=a.el),a.url&&(this.url=a.url),a.data&&this.populate(a.data));this.uri&&(this.collection.url=this.uri);if(!this.schema)return this.isInitalized=!1;this.isInitalized||(this.columns=this.schema.properties,this.collection.schema=this.schema,this.isInitalized=!0);return this.isInitalized},fetch:function(){this.collection.fetch()},populate:function(a){this.data=a;this.collection.reset(this.data)},
render:function(){if(this.el){var a=c.Utility.isString(this.el)?document.querySelector(this.el):this.el;a&&(this.template=this.compileTemplate(),a.innerHTML=this.template)}return this},compileTemplate:function(){var a=this.columns,c=this.data,b="<table>";if(a){var b=b+"<thead><tr>",d;for(d in a)a.hasOwnProperty(d)&&(b=b+"<th>"+d+"</th>");b+="</tr></thead>"}if(c){for(var b=b+"<tbody>",f,g,a=0;a<c.length;a++){d=c[a];b+="<tr>";for(f in d)d.hasOwnProperty(f)&&(g=d[f],b=b+"<td>"+g+"</td>");b+="</tr>"}b+=
"</tbody>"}return b+"</table>"},setURI:function(a){this.uri=a},setSchema:function(a){this.schema=a;this.columns=a.properties;this.collection.reset();this.collection.schema=a;this.uri&&(col.url=this.uri)}});c.Presentation.AutoTable=c.Presentation.AutomaticTable;return c.Presentation});